-- ============================================================================
-- ANALYTICS LAYER: Business-Ready Views and KPIs
-- Creates analytical views using watermarked data for business intelligence
-- ============================================================================

USE DATABASE FIN_TRADE_EXTRACT;
USE WAREHOUSE FIN_TRADE_WH;
USE SCHEMA ANALYTICS;

-- ============================================================================
-- STEP 1: Current Financial Snapshot (Latest Data)
-- ============================================================================

CREATE OR REPLACE VIEW CURRENT_FINANCIAL_SNAPSHOT AS
WITH latest_data AS (
    SELECT 
        *,
        ROW_NUMBER() OVER (PARTITION BY SYMBOL ORDER BY LOAD_TIMESTAMP DESC) as rn
    FROM FIN_TRADE_EXTRACT.RAW.OVERVIEW
)
SELECT 
    SYMBOL,
    NAME as COMPANY_NAME,
    SECTOR,
    INDUSTRY,
    EXCHANGE,
    COUNTRY,
    
    -- Valuation Metrics
    ROUND(MARKET_CAPITALIZATION / 1000000000, 2) as MARKET_CAP_BILLIONS,
    PE_RATIO,
    PRICE_TO_BOOK_RATIO,
    PRICE_TO_SALES_RATIO_TTM,
    EV_TO_EBITDA,
    
    -- Profitability Metrics
    PROFIT_MARGIN * 100 as PROFIT_MARGIN_PCT,
    OPERATING_MARGIN_TTM * 100 as OPERATING_MARGIN_PCT,
    RETURN_ON_ASSETS_TTM * 100 as ROA_PCT,
    RETURN_ON_EQUITY_TTM * 100 as ROE_PCT,
    
    -- Growth Metrics
    QUARTERLY_EARNINGS_GROWTH_YOY * 100 as QUARTERLY_EARNINGS_GROWTH_PCT,
    QUARTERLY_REVENUE_GROWTH_YOY * 100 as QUARTERLY_REVENUE_GROWTH_PCT,
    
    -- Dividend Information
    DIVIDEND_YIELD * 100 as DIVIDEND_YIELD_PCT,
    DIVIDEND_PER_SHARE,
    DIVIDEND_DATE,
    
    -- Trading Metrics
    BETA,
    WEEK_52_HIGH,
    WEEK_52_LOW,
    DAY_50_MOVING_AVERAGE,
    DAY_200_MOVING_AVERAGE,
    
    -- Data Quality
    LOAD_TIMESTAMP as LAST_UPDATED,
    BATCH_ID,
    DATEDIFF('hour', LOAD_TIMESTAMP, CURRENT_TIMESTAMP) as HOURS_SINCE_UPDATE
    
FROM latest_data
WHERE rn = 1
AND NAME IS NOT NULL;

-- ============================================================================
-- STEP 2: Market Cap Rankings and Classifications
-- ============================================================================

CREATE OR REPLACE VIEW MARKET_CAP_RANKINGS AS
SELECT 
    ROW_NUMBER() OVER (ORDER BY MARKET_CAPITALIZATION DESC) as RANK,
    SYMBOL,
    COMPANY_NAME,
    SECTOR,
    MARKET_CAP_BILLIONS,
    
    -- Market Cap Classification
    CASE 
        WHEN MARKET_CAP_BILLIONS >= 200 THEN 'MEGA_CAP'
        WHEN MARKET_CAP_BILLIONS >= 10 THEN 'LARGE_CAP'
        WHEN MARKET_CAP_BILLIONS >= 2 THEN 'MID_CAP'
        WHEN MARKET_CAP_BILLIONS >= 0.3 THEN 'SMALL_CAP'
        ELSE 'MICRO_CAP'
    END as CAP_CLASSIFICATION,
    
    PE_RATIO,
    ROE_PCT,
    DIVIDEND_YIELD_PCT,
    LAST_UPDATED
    
FROM CURRENT_FINANCIAL_SNAPSHOT
WHERE MARKET_CAP_BILLIONS IS NOT NULL
ORDER BY RANK;

-- ============================================================================
-- STEP 3: Sector Performance Analysis
-- ============================================================================

CREATE OR REPLACE VIEW SECTOR_PERFORMANCE AS
SELECT 
    SECTOR,
    COUNT(*) as COMPANY_COUNT,
    
    -- Market Cap Metrics
    ROUND(SUM(MARKET_CAP_BILLIONS), 2) as TOTAL_MARKET_CAP_BILLIONS,
    ROUND(AVG(MARKET_CAP_BILLIONS), 2) as AVG_MARKET_CAP_BILLIONS,
    ROUND(MEDIAN(MARKET_CAP_BILLIONS), 2) as MEDIAN_MARKET_CAP_BILLIONS,
    
    -- Valuation Metrics
    ROUND(AVG(PE_RATIO), 2) as AVG_PE_RATIO,
    ROUND(MEDIAN(PE_RATIO), 2) as MEDIAN_PE_RATIO,
    
    -- Profitability Metrics
    ROUND(AVG(PROFIT_MARGIN_PCT), 2) as AVG_PROFIT_MARGIN_PCT,
    ROUND(AVG(ROE_PCT), 2) as AVG_ROE_PCT,
    ROUND(AVG(ROA_PCT), 2) as AVG_ROA_PCT,
    
    -- Growth Metrics
    ROUND(AVG(QUARTERLY_EARNINGS_GROWTH_PCT), 2) as AVG_EARNINGS_GROWTH_PCT,
    ROUND(AVG(QUARTERLY_REVENUE_GROWTH_PCT), 2) as AVG_REVENUE_GROWTH_PCT,
    
    -- Dividend Metrics
    ROUND(AVG(DIVIDEND_YIELD_PCT), 2) as AVG_DIVIDEND_YIELD_PCT,
    COUNT(CASE WHEN DIVIDEND_YIELD_PCT > 0 THEN 1 END) as DIVIDEND_PAYING_COMPANIES,
    
    -- Risk Metrics
    ROUND(AVG(BETA), 2) as AVG_BETA,
    
    MAX(LAST_UPDATED) as LAST_SECTOR_UPDATE
    
FROM CURRENT_FINANCIAL_SNAPSHOT
WHERE SECTOR IS NOT NULL
GROUP BY SECTOR
ORDER BY TOTAL_MARKET_CAP_BILLIONS DESC;

-- ============================================================================
-- STEP 4: Investment Screening Views
-- ============================================================================

-- High Quality Dividend Stocks
CREATE OR REPLACE VIEW HIGH_QUALITY_DIVIDEND_STOCKS AS
SELECT 
    RANK,
    SYMBOL,
    COMPANY_NAME,
    SECTOR,
    MARKET_CAP_BILLIONS,
    DIVIDEND_YIELD_PCT,
    PE_RATIO,
    ROE_PCT,
    PROFIT_MARGIN_PCT,
    BETA,
    LAST_UPDATED
FROM MARKET_CAP_RANKINGS
WHERE DIVIDEND_YIELD_PCT >= 2.0  -- At least 2% dividend yield
  AND PE_RATIO BETWEEN 5 AND 25  -- Reasonable valuation
  AND ROE_PCT >= 10               -- Strong return on equity
  AND PROFIT_MARGIN_PCT >= 5      -- Profitable companies
  AND MARKET_CAP_BILLIONS >= 1    -- Mid cap and above
ORDER BY DIVIDEND_YIELD_PCT DESC, MARKET_CAP_BILLIONS DESC;

-- Growth Stocks (High Growth, Higher Risk)
CREATE OR REPLACE VIEW HIGH_GROWTH_STOCKS AS
SELECT 
    RANK,
    SYMBOL,
    COMPANY_NAME,
    SECTOR,
    MARKET_CAP_BILLIONS,
    QUARTERLY_EARNINGS_GROWTH_PCT,
    QUARTERLY_REVENUE_GROWTH_PCT,
    PE_RATIO,
    ROE_PCT,
    BETA,
    LAST_UPDATED
FROM MARKET_CAP_RANKINGS m
JOIN CURRENT_FINANCIAL_SNAPSHOT c ON m.SYMBOL = c.SYMBOL
WHERE (QUARTERLY_EARNINGS_GROWTH_PCT >= 15 OR QUARTERLY_REVENUE_GROWTH_PCT >= 10)
  AND MARKET_CAP_BILLIONS >= 1
  AND PE_RATIO IS NOT NULL
ORDER BY QUARTERLY_EARNINGS_GROWTH_PCT DESC NULLS LAST;

-- Value Stocks (Low PE, Strong Fundamentals)
CREATE OR REPLACE VIEW VALUE_STOCKS AS
SELECT 
    RANK,
    SYMBOL,
    COMPANY_NAME,
    SECTOR,
    MARKET_CAP_BILLIONS,
    PE_RATIO,
    PRICE_TO_BOOK_RATIO,
    ROE_PCT,
    ROA_PCT,
    PROFIT_MARGIN_PCT,
    LAST_UPDATED
FROM MARKET_CAP_RANKINGS m
JOIN CURRENT_FINANCIAL_SNAPSHOT c ON m.SYMBOL = c.SYMBOL
WHERE PE_RATIO BETWEEN 5 AND 15        -- Low to moderate PE
  AND PRICE_TO_BOOK_RATIO BETWEEN 0.5 AND 2  -- Reasonable P/B ratio
  AND ROE_PCT >= 8                      -- Decent returns
  AND PROFIT_MARGIN_PCT >= 3            -- Profitable
  AND MARKET_CAP_BILLIONS >= 2          -- Large enough companies
ORDER BY PE_RATIO ASC, ROE_PCT DESC;

-- ============================================================================
-- STEP 5: Data Quality and Monitoring Dashboard
-- ============================================================================

CREATE OR REPLACE VIEW DATA_QUALITY_DASHBOARD AS
WITH data_completeness AS (
    SELECT 
        BATCH_ID,
        LOAD_TIMESTAMP,
        COUNT(*) as TOTAL_RECORDS,
        COUNT(DISTINCT SYMBOL) as UNIQUE_SYMBOLS,
        
        -- Completeness Metrics
        ROUND(COUNT(CASE WHEN NAME IS NOT NULL THEN 1 END) * 100.0 / COUNT(*), 1) as NAME_COMPLETENESS_PCT,
        ROUND(COUNT(CASE WHEN MARKET_CAPITALIZATION IS NOT NULL THEN 1 END) * 100.0 / COUNT(*), 1) as MARKET_CAP_COMPLETENESS_PCT,
        ROUND(COUNT(CASE WHEN PE_RATIO IS NOT NULL THEN 1 END) * 100.0 / COUNT(*), 1) as PE_COMPLETENESS_PCT,
        ROUND(COUNT(CASE WHEN SECTOR IS NOT NULL THEN 1 END) * 100.0 / COUNT(*), 1) as SECTOR_COMPLETENESS_PCT,
        
        -- Quality Metrics
        COUNT(CASE WHEN MARKET_CAPITALIZATION > 0 THEN 1 END) as VALID_MARKET_CAP_COUNT,
        COUNT(CASE WHEN PE_RATIO BETWEEN 1 AND 200 THEN 1 END) as REASONABLE_PE_COUNT,
        COUNT(CASE WHEN DIVIDEND_YIELD BETWEEN 0 AND 0.20 THEN 1 END) as REASONABLE_DIVIDEND_COUNT,
        
        DATEDIFF('hour', LOAD_TIMESTAMP, CURRENT_TIMESTAMP) as HOURS_SINCE_LOAD
        
    FROM FIN_TRADE_EXTRACT.RAW.OVERVIEW
    GROUP BY BATCH_ID, LOAD_TIMESTAMP
)
SELECT 
    *,
    CASE 
        WHEN HOURS_SINCE_LOAD <= 2 THEN 'VERY_FRESH'
        WHEN HOURS_SINCE_LOAD <= 24 THEN 'FRESH'
        WHEN HOURS_SINCE_LOAD <= 72 THEN 'STALE'
        ELSE 'VERY_STALE'
    END as DATA_FRESHNESS_STATUS,
    
    CASE 
        WHEN NAME_COMPLETENESS_PCT >= 90 AND MARKET_CAP_COMPLETENESS_PCT >= 80 THEN 'HIGH_QUALITY'
        WHEN NAME_COMPLETENESS_PCT >= 70 AND MARKET_CAP_COMPLETENESS_PCT >= 60 THEN 'MEDIUM_QUALITY'
        ELSE 'LOW_QUALITY'
    END as OVERALL_QUALITY_SCORE
    
FROM data_completeness
ORDER BY LOAD_TIMESTAMP DESC;

-- ============================================================================
-- STEP 6: Business KPI Summary
-- ============================================================================

CREATE OR REPLACE VIEW BUSINESS_KPI_SUMMARY AS
SELECT 
    'PORTFOLIO_OVERVIEW' as KPI_CATEGORY,
    COUNT(DISTINCT SYMBOL) as TOTAL_COMPANIES_TRACKED,
    COUNT(DISTINCT SECTOR) as SECTORS_COVERED,
    COUNT(DISTINCT EXCHANGE) as EXCHANGES_COVERED,
    ROUND(SUM(MARKET_CAP_BILLIONS), 1) as TOTAL_MARKET_CAP_BILLIONS,
    ROUND(AVG(MARKET_CAP_BILLIONS), 1) as AVG_MARKET_CAP_BILLIONS,
    ROUND(AVG(PE_RATIO), 1) as AVG_PE_RATIO,
    ROUND(AVG(DIVIDEND_YIELD_PCT), 2) as AVG_DIVIDEND_YIELD_PCT,
    MAX(LAST_UPDATED) as LAST_DATA_UPDATE
FROM CURRENT_FINANCIAL_SNAPSHOT

UNION ALL

SELECT 
    'HIGH_VALUE_OPPORTUNITIES' as KPI_CATEGORY,
    (SELECT COUNT(*) FROM HIGH_QUALITY_DIVIDEND_STOCKS) as DIVIDEND_OPPORTUNITIES,
    (SELECT COUNT(*) FROM HIGH_GROWTH_STOCKS) as GROWTH_OPPORTUNITIES,  
    (SELECT COUNT(*) FROM VALUE_STOCKS) as VALUE_OPPORTUNITIES,
    (SELECT ROUND(AVG(MARKET_CAP_BILLIONS), 1) FROM HIGH_QUALITY_DIVIDEND_STOCKS) as AVG_DIVIDEND_STOCK_SIZE,
    (SELECT ROUND(AVG(DIVIDEND_YIELD_PCT), 2) FROM HIGH_QUALITY_DIVIDEND_STOCKS) as AVG_DIVIDEND_YIELD,
    (SELECT ROUND(AVG(PE_RATIO), 1) FROM VALUE_STOCKS) as AVG_VALUE_STOCK_PE,
    NULL as AVG_DIVIDEND_YIELD_PCT,
    CURRENT_TIMESTAMP as LAST_DATA_UPDATE;

SELECT 'ANALYTICS LAYER COMPLETE' as status;
SELECT 'Query CURRENT_FINANCIAL_SNAPSHOT, MARKET_CAP_RANKINGS, or BUSINESS_KPI_SUMMARY for insights' as next_step;