-- ============================================================================
-- COMPREHENSIVE COLUMN FIX
-- Add all missing columns that exist in CSV but not in table
-- ============================================================================

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;

-- Check current table structure
DESC TABLE RAW.OVERVIEW;

-- Add all missing columns based on CSV structure
-- From the CSV header: SYMBOL_ID,SYMBOL,ASSET_TYPE,NAME,DESCRIPTION,CIK,EXCHANGE,CURRENCY,COUNTRY,SECTOR,INDUSTRY,ADDRESS,OFFICIAL_SITE,FISCAL_YEAR_END,MARKET_CAPITALIZATION,EBITDA,PE_RATIO,PEG_RATIO,BOOK_VALUE,DIVIDEND_PER_SHARE,DIVIDEND_YIELD,EPS,REVENUE_PER_SHARE_TTM,PROFIT_MARGIN,OPERATING_MARGIN_TTM,RETURN_ON_ASSETS_TTM,RETURN_ON_EQUITY_TTM,REVENUE_TTM,GROSS_PROFIT_TTM,DILUTED_EPS_TTM,QUARTERLY_EARNINGS_GROWTH_YOY,QUARTERLY_REVENUE_GROWTH_YOY,ANALYST_TARGET_PRICE,TRAILING_PE,FORWARD_PE,PRICE_TO_SALES_RATIO_TTM,PRICE_TO_BOOK_RATIO,EV_TO_REVENUE,EV_TO_EBITDA,BETA,WEEK_52_HIGH,WEEK_52_LOW,DAY_50_MOVING_AVERAGE,DAY_200_MOVING_AVERAGE,SHARES_OUTSTANDING,DIVIDEND_DATE,EX_DIVIDEND_DATE,API_RESPONSE_STATUS,CREATED_AT,UPDATED_AT

-- Add columns that likely don't exist
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS OFFICIAL_SITE VARCHAR(500);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS DAY_50_MOVING_AVERAGE FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS DAY_200_MOVING_AVERAGE FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS WEEK_52_HIGH FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS WEEK_52_LOW FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS BETA FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS EV_TO_REVENUE FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS EV_TO_EBITDA FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS PRICE_TO_BOOK_RATIO FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS PRICE_TO_SALES_RATIO_TTM FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS FORWARD_PE FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS TRAILING_PE FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS ANALYST_TARGET_PRICE FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS QUARTERLY_REVENUE_GROWTH_YOY FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS QUARTERLY_EARNINGS_GROWTH_YOY FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS DILUTED_EPS_TTM FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS GROSS_PROFIT_TTM FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS REVENUE_TTM FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS RETURN_ON_EQUITY_TTM FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS RETURN_ON_ASSETS_TTM FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS OPERATING_MARGIN_TTM FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS PROFIT_MARGIN FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS REVENUE_PER_SHARE_TTM FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS EPS FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS DIVIDEND_YIELD FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS DIVIDEND_PER_SHARE FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS BOOK_VALUE FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS PEG_RATIO FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS PE_RATIO FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS EBITDA FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS MARKET_CAPITALIZATION FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS FISCAL_YEAR_END VARCHAR(50);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS ADDRESS VARCHAR(500);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS INDUSTRY VARCHAR(200);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS SECTOR VARCHAR(200);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS COUNTRY VARCHAR(100);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS CURRENCY VARCHAR(10);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS EXCHANGE VARCHAR(50);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS CIK VARCHAR(50);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS DESCRIPTION TEXT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS NAME VARCHAR(500);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS ASSET_TYPE VARCHAR(100);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS SYMBOL VARCHAR(20);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS SYMBOL_ID VARCHAR(50);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS SHARES_OUTSTANDING FLOAT;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS DIVIDEND_DATE DATE;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS EX_DIVIDEND_DATE DATE;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS API_RESPONSE_STATUS VARCHAR(50);
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP;
ALTER TABLE RAW.OVERVIEW ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP;

-- Verify the table structure now
DESC TABLE RAW.OVERVIEW;

-- Try a simple load without explicit column mapping to let Snowflake auto-map
COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_035238_aad23b30.csv')
FILE_FORMAT = (
    TYPE = 'CSV' 
    SKIP_HEADER = 1 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = 'CONTINUE';

-- Check if records were loaded
SELECT COUNT(*) as total_records FROM RAW.OVERVIEW;

-- If successful, load the rest of the files
COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_035431_559ca0e6.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_035537_6cbdb789.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_035702_49a938d1.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_125259_5c81f779.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_125427_6e8be71b.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_125458_6d0eb07b.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_125529_aca3aa9e.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

-- Final verification
SELECT COUNT(*) as total_records_final FROM RAW.OVERVIEW;
SELECT COUNT(DISTINCT SYMBOL) as unique_companies FROM RAW.OVERVIEW;

-- Show sample of new data
SELECT SYMBOL, NAME, SECTOR, MARKET_CAPITALIZATION, CREATED_AT
FROM RAW.OVERVIEW 
WHERE CREATED_AT >= CURRENT_DATE()
ORDER BY CREATED_AT DESC 
LIMIT 10;