-- ============================================================================
-- ALIGN WITH ORIGINAL SCHEMA
-- Recreate OVERVIEW table to match the original extractor design
-- Focus on core company descriptors only
-- ============================================================================

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;

-- Check current table structure
SELECT COUNT(*) as current_records FROM RAW.OVERVIEW;

-- Backup existing data before dropping (optional safety measure)
CREATE OR REPLACE TABLE RAW.OVERVIEW_BACKUP AS SELECT * FROM RAW.OVERVIEW;

-- Drop the current table with all the extra columns
DROP TABLE RAW.OVERVIEW;

-- Recreate with the original simple schema matching extract_overview.py
CREATE OR REPLACE TABLE RAW.OVERVIEW (
    OVERVIEW_ID     NUMBER AUTOINCREMENT PRIMARY KEY,
    SYMBOL_ID       VARCHAR(50),
    SYMBOL          VARCHAR(20) NOT NULL,    
    ASSETTYPE       VARCHAR(50),
    NAME            VARCHAR(255),   
    DESCRIPTION     TEXT,   
    CIK             VARCHAR(20),   
    EXCHANGE        VARCHAR(50),   
    CURRENCY        VARCHAR(10),   
    COUNTRY         VARCHAR(100),   
    SECTOR          VARCHAR(100),   
    INDUSTRY        VARCHAR(200),   
    ADDRESS         TEXT,   
    OFFICIALSITE    VARCHAR(255),   
    FISCALYEAREND   VARCHAR(20),
    STATUS          VARCHAR(20),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Add audit columns for Snowflake
    LOAD_TIMESTAMP  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    BATCH_ID        VARCHAR(100),
    SOURCE_FILE_NAME VARCHAR(500)
);

-- Verify the new table structure
DESC TABLE RAW.OVERVIEW;

-- Now load data with direct column mapping - SIMPLEST POSSIBLE SYNTAX
COPY INTO RAW.OVERVIEW (
    SYMBOL_ID, SYMBOL, ASSETTYPE, NAME, DESCRIPTION, CIK, EXCHANGE, 
    CURRENCY, COUNTRY, SECTOR, INDUSTRY, ADDRESS, OFFICIALSITE, 
    FISCALYEAREND, STATUS, CREATED_AT, UPDATED_AT
)
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_035238_aad23b30.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

-- Check if records were loaded
SELECT COUNT(*) as records_after_first_file FROM RAW.OVERVIEW;

-- Update existing records to add missing audit fields
UPDATE RAW.OVERVIEW 
SET 
    BATCH_ID = 'MANUAL_LOAD_20250928',
    SOURCE_FILE_NAME = 'overview_20250928_035238_aad23b30.csv'
WHERE BATCH_ID IS NULL;

-- Load the rest of the files with simple direct mapping
-- Load each file individually to avoid complex subqueries
COPY INTO RAW.OVERVIEW (
    SYMBOL_ID, SYMBOL, ASSETTYPE, NAME, DESCRIPTION, CIK, EXCHANGE, 
    CURRENCY, COUNTRY, SECTOR, INDUSTRY, ADDRESS, OFFICIALSITE, 
    FISCALYEAREND, STATUS, CREATED_AT, UPDATED_AT
)
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_035431_559ca0e6.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

-- Update the batch info for this file
UPDATE RAW.OVERVIEW 
SET BATCH_ID = 'MANUAL_LOAD_20250928', 
    SOURCE_FILE_NAME = 'overview_20250928_035431_559ca0e6.csv'
WHERE BATCH_ID IS NULL;

-- Load file 3
COPY INTO RAW.OVERVIEW (
    SYMBOL_ID, SYMBOL, ASSETTYPE, NAME, DESCRIPTION, CIK, EXCHANGE, 
    CURRENCY, COUNTRY, SECTOR, INDUSTRY, ADDRESS, OFFICIALSITE, 
    FISCALYEAREND, STATUS, CREATED_AT, UPDATED_AT
)
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_035537_6cbdb789.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

UPDATE RAW.OVERVIEW 
SET BATCH_ID = 'MANUAL_LOAD_20250928', 
    SOURCE_FILE_NAME = 'overview_20250928_035537_6cbdb789.csv'
WHERE BATCH_ID IS NULL;

-- Load file 4
COPY INTO RAW.OVERVIEW (
    SYMBOL_ID, SYMBOL, ASSETTYPE, NAME, DESCRIPTION, CIK, EXCHANGE, 
    CURRENCY, COUNTRY, SECTOR, INDUSTRY, ADDRESS, OFFICIALSITE, 
    FISCALYEAREND, STATUS, CREATED_AT, UPDATED_AT
)
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_035702_49a938d1.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

UPDATE RAW.OVERVIEW 
SET BATCH_ID = 'MANUAL_LOAD_20250928', 
    SOURCE_FILE_NAME = 'overview_20250928_035702_49a938d1.csv'
WHERE BATCH_ID IS NULL;

-- Load file 5
COPY INTO RAW.OVERVIEW (
    SYMBOL_ID, SYMBOL, ASSETTYPE, NAME, DESCRIPTION, CIK, EXCHANGE, 
    CURRENCY, COUNTRY, SECTOR, INDUSTRY, ADDRESS, OFFICIALSITE, 
    FISCALYEAREND, STATUS, CREATED_AT, UPDATED_AT
)
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_125259_5c81f779.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

UPDATE RAW.OVERVIEW 
SET BATCH_ID = 'MANUAL_LOAD_20250928', 
    SOURCE_FILE_NAME = 'overview_20250928_125259_5c81f779.csv'
WHERE BATCH_ID IS NULL;

-- Load file 6
COPY INTO RAW.OVERVIEW (
    SYMBOL_ID, SYMBOL, ASSETTYPE, NAME, DESCRIPTION, CIK, EXCHANGE, 
    CURRENCY, COUNTRY, SECTOR, INDUSTRY, ADDRESS, OFFICIALSITE, 
    FISCALYEAREND, STATUS, CREATED_AT, UPDATED_AT
)
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_125427_6e8be71b.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

UPDATE RAW.OVERVIEW 
SET BATCH_ID = 'MANUAL_LOAD_20250928', 
    SOURCE_FILE_NAME = 'overview_20250928_125427_6e8be71b.csv'
WHERE BATCH_ID IS NULL;

-- Load file 7
COPY INTO RAW.OVERVIEW (
    SYMBOL_ID, SYMBOL, ASSETTYPE, NAME, DESCRIPTION, CIK, EXCHANGE, 
    CURRENCY, COUNTRY, SECTOR, INDUSTRY, ADDRESS, OFFICIALSITE, 
    FISCALYEAREND, STATUS, CREATED_AT, UPDATED_AT
)
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_125458_6d0eb07b.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

UPDATE RAW.OVERVIEW 
SET BATCH_ID = 'MANUAL_LOAD_20250928', 
    SOURCE_FILE_NAME = 'overview_20250928_125458_6d0eb07b.csv'
WHERE BATCH_ID IS NULL;

-- Load file 8
COPY INTO RAW.OVERVIEW (
    SYMBOL_ID, SYMBOL, ASSETTYPE, NAME, DESCRIPTION, CIK, EXCHANGE, 
    CURRENCY, COUNTRY, SECTOR, INDUSTRY, ADDRESS, OFFICIALSITE, 
    FISCALYEAREND, STATUS, CREATED_AT, UPDATED_AT
)
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_125529_aca3aa9e.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

UPDATE RAW.OVERVIEW 
SET BATCH_ID = 'MANUAL_LOAD_20250928', 
    SOURCE_FILE_NAME = 'overview_20250928_125529_aca3aa9e.csv'
WHERE BATCH_ID IS NULL;

-- Final verification - should now have 300+ companies
SELECT COUNT(*) as total_records FROM RAW.OVERVIEW;
SELECT COUNT(DISTINCT SYMBOL) as unique_companies FROM RAW.OVERVIEW;

-- Show sample of the clean, focused data
SELECT 
    SYMBOL, 
    NAME, 
    SECTOR, 
    INDUSTRY, 
    EXCHANGE,
    COUNTRY,
    STATUS,
    CREATED_AT
FROM RAW.OVERVIEW 
WHERE STATUS = 'success'
ORDER BY CREATED_AT DESC 
LIMIT 15;

-- Show summary by sector (core company descriptors focus)
SELECT 
    SECTOR,
    COUNT(*) as company_count,
    COUNT(DISTINCT EXCHANGE) as exchanges
FROM RAW.OVERVIEW 
WHERE STATUS = 'success'
GROUP BY SECTOR 
ORDER BY company_count DESC;