-- Quick check to see actual column names in OVERVIEW table
USE DATABASE FIN_TRADE_EXTRACT;
USE WAREHOUSE FIN_TRADE_WH;
USE SCHEMA RAW;

-- Show all columns in the OVERVIEW table
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'RAW' 
AND TABLE_NAME = 'OVERVIEW'
AND COLUMN_NAME LIKE '%MOVING%'
ORDER BY ORDINAL_POSITION;

-- Also check for any column with 50 or 200 in the name
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'RAW' 
AND TABLE_NAME = 'OVERVIEW'
AND (COLUMN_NAME LIKE '%50%' OR COLUMN_NAME LIKE '%200%')
ORDER BY ORDINAL_POSITION;