-- ============================================================================
-- EMERGENCY COLUMN FIX
-- Add missing OFFICIAL_SITE column and load data
-- ============================================================================

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;

-- Check current table structure
DESC TABLE RAW.OVERVIEW;

-- Add the missing OFFICIAL_SITE column
ALTER TABLE RAW.OVERVIEW 
ADD COLUMN OFFICIAL_SITE VARCHAR(500);

-- Verify the column was added
DESC TABLE RAW.OVERVIEW;

-- Now try loading with the corrected column mapping
COPY INTO RAW.OVERVIEW (
    SYMBOL_ID, SYMBOL, ASSET_TYPE, NAME, DESCRIPTION, CIK, EXCHANGE, 
    CURRENCY, COUNTRY, SECTOR, INDUSTRY, ADDRESS, OFFICIAL_SITE, 
    FISCAL_YEAR_END, MARKET_CAPITALIZATION, EBITDA, PE_RATIO, PEG_RATIO, 
    BOOK_VALUE, DIVIDEND_PER_SHARE, DIVIDEND_YIELD, EPS, REVENUE_PER_SHARE_TTM, 
    PROFIT_MARGIN, OPERATING_MARGIN_TTM, RETURN_ON_ASSETS_TTM, RETURN_ON_EQUITY_TTM, 
    REVENUE_TTM, GROSS_PROFIT_TTM, DILUTED_EPS_TTM, QUARTERLY_EARNINGS_GROWTH_YOY, 
    QUARTERLY_REVENUE_GROWTH_YOY, ANALYST_TARGET_PRICE, TRAILING_PE, FORWARD_PE, 
    PRICE_TO_SALES_RATIO_TTM, PRICE_TO_BOOK_RATIO, EV_TO_REVENUE, EV_TO_EBITDA, 
    BETA, WEEK_52_HIGH, WEEK_52_LOW, DAY_50_MOVING_AVERAGE, DAY_200_MOVING_AVERAGE, 
    SHARES_OUTSTANDING, DIVIDEND_DATE, EX_DIVIDEND_DATE, API_RESPONSE_STATUS, 
    CREATED_AT, UPDATED_AT
)
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_035238_aad23b30.csv')
FILE_FORMAT = (
    TYPE = 'CSV' 
    SKIP_HEADER = 1 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = 'CONTINUE';

-- Check if records were loaded
SELECT COUNT(*) as total_records FROM RAW.OVERVIEW;

-- Load the other large files now that the column is fixed
COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_035431_559ca0e6.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_035537_6cbdb789.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_035702_49a938d1.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_125259_5c81f779.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_125427_6e8be71b.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_125458_6d0eb07b.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
FILES = ('overview_20250928_125529_aca3aa9e.csv')
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

-- Final verification
SELECT COUNT(*) as total_records_final FROM RAW.OVERVIEW;
SELECT COUNT(DISTINCT SYMBOL) as unique_companies FROM RAW.OVERVIEW;

-- Show sample of new data
SELECT SYMBOL, NAME, SECTOR, OFFICIAL_SITE, MARKET_CAPITALIZATION
FROM RAW.OVERVIEW 
ORDER BY CREATED_AT DESC 
LIMIT 10;