-- ============================================================================
-- Snowflake Table Definition Fix for CSV Data Mismatch
-- This matches the ACTUAL CSV structure from Lambda functions
-- ============================================================================

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;

-- Drop and recreate OVERVIEW table with correct structure
DROP TABLE IF EXISTS OVERVIEW;

CREATE OR REPLACE TABLE OVERVIEW (
    -- Core identification fields (matches actual CSV)
    SYMBOL_ID                           VARCHAR(50),     -- Generated by Lambda
    SYMBOL                              VARCHAR(20),
    ASSET_TYPE                          VARCHAR(50),
    NAME                                VARCHAR(500),
    DESCRIPTION                         VARCHAR(16777216),
    CIK                                 VARCHAR(20),
    EXCHANGE                            VARCHAR(50),
    CURRENCY                            VARCHAR(10),
    COUNTRY                             VARCHAR(100),
    SECTOR                              VARCHAR(100),
    INDUSTRY                            VARCHAR(200),
    ADDRESS                             VARCHAR(16777216),
    OFFICIAL_SITE                       VARCHAR(500),    -- NEW COLUMN from CSV
    FISCAL_YEAR_END                     VARCHAR(50),     -- Increased size for actual data
    
    -- Financial metrics (matches CSV order)
    MARKET_CAPITALIZATION               NUMBER(20,0),
    EBITDA                              NUMBER(20,0),
    PE_RATIO                            NUMBER(10,4),
    PEG_RATIO                           NUMBER(10,4),
    BOOK_VALUE                          NUMBER(10,4),
    DIVIDEND_PER_SHARE                  NUMBER(10,4),
    DIVIDEND_YIELD                      NUMBER(8,6),
    EPS                                 NUMBER(10,4),
    REVENUE_PER_SHARE_TTM               NUMBER(10,4),
    PROFIT_MARGIN                       NUMBER(8,6),
    OPERATING_MARGIN_TTM                NUMBER(8,6),
    RETURN_ON_ASSETS_TTM                NUMBER(8,6),
    RETURN_ON_EQUITY_TTM                NUMBER(8,6),
    REVENUE_TTM                         NUMBER(20,0),
    GROSS_PROFIT_TTM                    NUMBER(20,0),
    DILUTED_EPS_TTM                     NUMBER(10,4),
    QUARTERLY_EARNINGS_GROWTH_YOY       NUMBER(8,6),
    QUARTERLY_REVENUE_GROWTH_YOY        NUMBER(8,6),
    ANALYST_TARGET_PRICE                NUMBER(10,4),
    TRAILING_PE                         NUMBER(10,4),
    FORWARD_PE                          NUMBER(10,4),
    PRICE_TO_SALES_RATIO_TTM            NUMBER(10,4),
    PRICE_TO_BOOK_RATIO                 NUMBER(10,4),
    EV_TO_REVENUE                       NUMBER(10,4),
    EV_TO_EBITDA                        NUMBER(10,4),
    BETA                                NUMBER(8,6),
    WEEK_52_HIGH                        NUMBER(12,4),
    WEEK_52_LOW                         NUMBER(12,4),
    DAY_50_MOVING_AVERAGE               NUMBER(12,4),    -- CORRECTED COLUMN NAME
    DAY_200_MOVING_AVERAGE              NUMBER(12,4),    -- CORRECTED COLUMN NAME
    SHARES_OUTSTANDING                  NUMBER(20,0),
    DIVIDEND_DATE                       DATE,
    EX_DIVIDEND_DATE                    DATE,
    
    -- Lambda metadata (matches CSV)
    API_RESPONSE_STATUS                 VARCHAR(50),     -- NEW COLUMN from CSV
    CREATED_AT                          TIMESTAMP,       -- NEW COLUMN from CSV
    UPDATED_AT                          TIMESTAMP,       -- NEW COLUMN from CSV
    
    -- Snowflake metadata
    LOADED_AT                           TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Company overview data from Lambda CSV files - corrected structure'
CLUSTER BY (SYMBOL);

-- Show the updated table structure
DESC TABLE OVERVIEW;

-- Test loading data now
COPY INTO OVERVIEW 
FROM @OVERVIEW_STAGE 
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT')
ON_ERROR = 'CONTINUE'
RETURN_FAILED_ONLY = FALSE;

-- Check if data loaded successfully
SELECT COUNT(*) AS total_rows FROM OVERVIEW;
SELECT * FROM OVERVIEW LIMIT 3;