-- ============================================================================
-- Snowflake Table Definitions for CSV Data from Lambda Functions
-- Column names and order match the CSV output exactly
-- ============================================================================

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;

-- ============================================================================
-- COMPANY OVERVIEW DATA (matches CSV exactly)
-- ============================================================================

CREATE OR REPLACE TABLE OVERVIEW (
    -- Core identification fields (matches actual CSV from Lambda)
    SYMBOL_ID                           VARCHAR(50),     -- Generated by Lambda
    SYMBOL                              VARCHAR(20),
    ASSET_TYPE                          VARCHAR(50),
    NAME                                VARCHAR(500),
    DESCRIPTION                         VARCHAR(16777216),
    CIK                                 VARCHAR(20),
    EXCHANGE                            VARCHAR(50),
    CURRENCY                            VARCHAR(10),
    COUNTRY                             VARCHAR(100),
    SECTOR                              VARCHAR(100),
    INDUSTRY                            VARCHAR(200),
    ADDRESS                             VARCHAR(16777216),
    OFFICIAL_SITE                       VARCHAR(500),    -- NEW: matches CSV
    FISCAL_YEAR_END                     VARCHAR(50),     -- INCREASED: was too small
    
    -- Financial metrics (matches CSV order and names)
    MARKET_CAPITALIZATION               NUMBER(20,0),
    EBITDA                              NUMBER(20,0),
    PE_RATIO                            NUMBER(10,4),
    PEG_RATIO                           NUMBER(10,4),
    BOOK_VALUE                          NUMBER(10,4),
    DIVIDEND_PER_SHARE                  NUMBER(10,4),
    DIVIDEND_YIELD                      NUMBER(8,6),
    EPS                                 NUMBER(10,4),
    REVENUE_PER_SHARE_TTM               NUMBER(10,4),
    PROFIT_MARGIN                       NUMBER(8,6),
    OPERATING_MARGIN_TTM                NUMBER(8,6),
    RETURN_ON_ASSETS_TTM                NUMBER(8,6),
    RETURN_ON_EQUITY_TTM                NUMBER(8,6),
    REVENUE_TTM                         NUMBER(20,0),
    GROSS_PROFIT_TTM                    NUMBER(20,0),
    DILUTED_EPS_TTM                     NUMBER(10,4),
    QUARTERLY_EARNINGS_GROWTH_YOY       NUMBER(8,6),
    QUARTERLY_REVENUE_GROWTH_YOY        NUMBER(8,6),
    ANALYST_TARGET_PRICE                NUMBER(10,4),
    TRAILING_PE                         NUMBER(10,4),
    FORWARD_PE                          NUMBER(10,4),
    PRICE_TO_SALES_RATIO_TTM            NUMBER(10,4),
    PRICE_TO_BOOK_RATIO                 NUMBER(10,4),
    EV_TO_REVENUE                       NUMBER(10,4),
    EV_TO_EBITDA                        NUMBER(10,4),
    BETA                                NUMBER(8,6),
    WEEK_52_HIGH                        NUMBER(12,4),
    WEEK_52_LOW                         NUMBER(12,4),
    DAY_50_MOVING_AVERAGE               NUMBER(12,4),    -- CORRECTED: matches CSV
    DAY_200_MOVING_AVERAGE              NUMBER(12,4),    -- CORRECTED: matches CSV
    SHARES_OUTSTANDING                  NUMBER(20,0),
    DIVIDEND_DATE                       DATE,
    EX_DIVIDEND_DATE                    DATE,
    
    -- Lambda metadata (matches CSV)
    API_RESPONSE_STATUS                 VARCHAR(50),     -- NEW: from CSV
    CREATED_AT                          TIMESTAMP,       -- NEW: from CSV  
    UPDATED_AT                          TIMESTAMP,       -- NEW: from CSV
    
    -- Snowflake metadata
    LOADED_AT                           TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Company overview data from Lambda CSV files'
CLUSTER BY (SYMBOL);

-- ============================================================================
-- TIME SERIES DAILY DATA (matches CSV exactly)
-- ============================================================================

CREATE OR REPLACE TABLE TIME_SERIES_DAILY_ADJUSTED (
    SYMBOL_ID                          VARCHAR(50),     -- Generated by Lambda
    DATE                               DATE,
    OPEN                               NUMBER(15,4),
    HIGH                               NUMBER(15,4),
    LOW                                NUMBER(15,4),
    CLOSE                              NUMBER(15,4),
    ADJUSTED_CLOSE                     NUMBER(15,4),
    VOLUME                             NUMBER(20,0),
    DIVIDEND_AMOUNT                    NUMBER(15,6),
    SPLIT_COEFFICIENT                  NUMBER(10,6),
    
    -- Metadata
    LOADED_AT                          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Daily time series data from Lambda CSV files'
CLUSTER BY (DATE, SYMBOL_ID);

-- ============================================================================
-- INCOME STATEMENT DATA (matches CSV exactly)
-- ============================================================================

CREATE OR REPLACE TABLE INCOME_STATEMENT (
    SYMBOL_ID                           VARCHAR(50),     -- Generated by Lambda
    FISCAL_DATE_ENDING                  DATE,
    REPORTED_CURRENCY                   VARCHAR(10),
    GROSS_PROFIT                        NUMBER(20,0),
    TOTAL_REVENUE                       NUMBER(20,0),
    COST_OF_REVENUE                     NUMBER(20,0),
    COST_OF_GOODS_AND_SERVICES_SOLD     NUMBER(20,0),
    OPERATING_INCOME                    NUMBER(20,0),
    SELLING_GENERAL_AND_ADMINISTRATIVE  NUMBER(20,0),
    RESEARCH_AND_DEVELOPMENT            NUMBER(20,0),
    OPERATING_EXPENSES                  NUMBER(20,0),
    INVESTMENT_INCOME_NET               NUMBER(20,0),
    NET_INTEREST_INCOME                 NUMBER(20,0),
    INTEREST_INCOME                     NUMBER(20,0),
    INTEREST_EXPENSE                    NUMBER(20,0),
    NON_INTEREST_INCOME                 NUMBER(20,0),
    OTHER_NON_OPERATING_INCOME          NUMBER(20,0),
    DEPRECIATION                        NUMBER(20,0),
    DEPRECIATION_AND_AMORTIZATION       NUMBER(20,0),
    INCOME_BEFORE_TAX                   NUMBER(20,0),
    INCOME_TAX_EXPENSE                  NUMBER(20,0),
    INTEREST_AND_DEBT_EXPENSE           NUMBER(20,0),
    NET_INCOME_FROM_CONTINUING_OPERATIONS NUMBER(20,0),
    COMPREHENSIVE_INCOME_NET_OF_TAX     NUMBER(20,0),
    EBIT                                NUMBER(20,0),
    EBITDA                              NUMBER(20,0),
    NET_INCOME                          NUMBER(20,0),
    
    -- Metadata
    LOADED_AT                           TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Income statement data from Lambda CSV files'
CLUSTER BY (SYMBOL_ID, FISCAL_DATE_ENDING);

-- ============================================================================
-- BALANCE SHEET DATA (matches CSV exactly)  
-- ============================================================================

CREATE OR REPLACE TABLE BALANCE_SHEET (
    SYMBOL_ID                               VARCHAR(50),     -- Generated by Lambda
    FISCAL_DATE_ENDING                      DATE,
    REPORTED_CURRENCY                       VARCHAR(10),
    TOTAL_ASSETS                            NUMBER(20,0),
    TOTAL_CURRENT_ASSETS                    NUMBER(20,0),
    CASH_AND_CASH_EQUIVALENTS_AT_CARRYING_VALUE NUMBER(20,0),
    CASH_AND_SHORT_TERM_INVESTMENTS         NUMBER(20,0),
    INVENTORY                               NUMBER(20,0),
    CURRENT_NET_RECEIVABLES                 NUMBER(20,0),
    TOTAL_NON_CURRENT_ASSETS                NUMBER(20,0),
    PROPERTY_PLANT_EQUIPMENT                NUMBER(20,0),
    ACCUMULATED_DEPRECIATION_AMORTIZATION_PPE NUMBER(20,0),
    INTANGIBLE_ASSETS                       NUMBER(20,0),
    INTANGIBLE_ASSETS_EXCLUDING_GOODWILL    NUMBER(20,0),
    GOODWILL                                NUMBER(20,0),
    INVESTMENTS                             NUMBER(20,0),
    LONG_TERM_INVESTMENTS                   NUMBER(20,0),
    SHORT_TERM_INVESTMENTS                  NUMBER(20,0),
    OTHER_CURRENT_ASSETS                    NUMBER(20,0),
    OTHER_NON_CURRENT_ASSETS                NUMBER(20,0),
    TOTAL_LIABILITIES                       NUMBER(20,0),
    TOTAL_CURRENT_LIABILITIES               NUMBER(20,0),
    CURRENT_ACCOUNTS_PAYABLE                NUMBER(20,0),
    DEFERRED_REVENUE                        NUMBER(20,0),
    CURRENT_DEBT                            NUMBER(20,0),
    SHORT_TERM_DEBT                         NUMBER(20,0),
    TOTAL_NON_CURRENT_LIABILITIES           NUMBER(20,0),
    CAPITAL_LEASE_OBLIGATIONS               NUMBER(20,0),
    LONG_TERM_DEBT                          NUMBER(20,0),
    CURRENT_LONG_TERM_DEBT                  NUMBER(20,0),
    LONG_TERM_DEBT_NONCURRENT               NUMBER(20,0),
    SHORT_LONG_TERM_DEBT_TOTAL              NUMBER(20,0),
    OTHER_CURRENT_LIABILITIES               NUMBER(20,0),
    OTHER_NON_CURRENT_LIABILITIES           NUMBER(20,0),
    TOTAL_SHAREHOLDER_EQUITY                NUMBER(20,0),
    TREASURY_STOCK                          NUMBER(20,0),
    RETAINED_EARNINGS                       NUMBER(20,0),
    COMMON_STOCK                            NUMBER(20,0),
    COMMON_STOCK_SHARES_OUTSTANDING         NUMBER(20,0),
    
    -- Metadata
    LOADED_AT                               TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Balance sheet data from Lambda CSV files'
CLUSTER BY (SYMBOL_ID, FISCAL_DATE_ENDING);

-- ============================================================================
-- CASH FLOW DATA (matches CSV exactly)
-- ============================================================================

CREATE OR REPLACE TABLE CASH_FLOW (
    SYMBOL_ID                                       VARCHAR(50),     -- Generated by Lambda
    FISCAL_DATE_ENDING                              DATE,
    REPORTED_CURRENCY                               VARCHAR(10),
    OPERATING_CASHFLOW                              NUMBER(20,0),
    PAYMENTS_FOR_OPERATING_ACTIVITIES               NUMBER(20,0),
    PROCEEDS_FROM_OPERATING_ACTIVITIES              NUMBER(20,0),
    CHANGE_IN_OPERATING_LIABILITIES                 NUMBER(20,0),
    CHANGE_IN_OPERATING_ASSETS                      NUMBER(20,0),
    DEPRECIATION_DEPLETION_AND_AMORTIZATION         NUMBER(20,0),
    CAPITAL_EXPENDITURES                            NUMBER(20,0),
    CHANGE_IN_RECEIVABLES                           NUMBER(20,0),
    CHANGE_IN_INVENTORY                             NUMBER(20,0),
    PROFIT_LOSS                                     NUMBER(20,0),
    CASHFLOW_FROM_INVESTMENT                        NUMBER(20,0),
    CASHFLOW_FROM_FINANCING                         NUMBER(20,0),
    PROCEEDS_FROM_REPAYMENTS_OF_SHORT_TERM_DEBT     NUMBER(20,0),
    PAYMENTS_FOR_REPURCHASE_OF_COMMON_STOCK         NUMBER(20,0),
    PAYMENTS_FOR_REPURCHASE_OF_EQUITY               NUMBER(20,0),
    PAYMENTS_FOR_REPURCHASE_OF_PREFERRED_STOCK      NUMBER(20,0),
    DIVIDEND_PAYOUT                                 NUMBER(20,0),
    DIVIDEND_PAYOUT_COMMON_STOCK                    NUMBER(20,0),
    DIVIDEND_PAYOUT_PREFERRED_STOCK                 NUMBER(20,0),
    PROCEEDS_FROM_ISSUANCE_OF_COMMON_STOCK          NUMBER(20,0),
    PROCEEDS_FROM_ISSUANCE_OF_LONG_TERM_DEBT_AND_CAPITAL_SECURITIES_NET NUMBER(20,0),
    PROCEEDS_FROM_ISSUANCE_OF_PREFERRED_STOCK       NUMBER(20,0),
    PROCEEDS_FROM_REPAYMENTS_OF_LONG_TERM_DEBT      NUMBER(20,0),
    PROCEEDS_FROM_SHORT_TERM_DEBT                   NUMBER(20,0),
    CHANGE_IN_CASH_AND_CASH_EQUIVALENTS             NUMBER(20,0),
    CHANGE_IN_EXCHANGE_RATE                         NUMBER(20,0),
    NET_INCOME                                      NUMBER(20,0),
    
    -- Metadata  
    LOADED_AT                                       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Cash flow data from Lambda CSV files'
CLUSTER BY (SYMBOL_ID, FISCAL_DATE_ENDING);

-- ============================================================================
-- SHOW CREATED TABLES
-- ============================================================================

SHOW TABLES IN SCHEMA RAW;

SELECT 
    TABLE_NAME,
    ROW_COUNT,
    BYTES,
    CLUSTERING_KEY,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'RAW' 
    AND TABLE_TYPE = 'BASE TABLE'
    AND TABLE_NAME IN ('OVERVIEW', 'TIME_SERIES_DAILY_ADJUSTED', 'INCOME_STATEMENT', 'BALANCE_SHEET', 'CASH_FLOW')
ORDER BY TABLE_NAME;