-- ============================================================================
-- Create Data Source Watermarks
-- 
-- This script creates watermark entries for specific data sources by copying
-- from the base LISTING_STATUS watermarks and applying appropriate filtering.
--
-- Usage: Run this script after the base ETL_WATERMARKS table is created
-- ============================================================================

-- Set context
USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;
USE WAREHOUSE FIN_TRADE_WH;
USE ROLE ETL_ROLE;

-- ============================================================================
-- TIME_SERIES_DAILY_ADJUSTED Watermarks
-- ============================================================================
-- All symbols are eligible for time series data (both active and delisted)

INSERT INTO FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS 
    (TABLE_NAME, SYMBOL_ID, SYMBOL, NAME, EXCHANGE, ASSET_TYPE, STATUS, API_ELIGIBLE, 
     IPO_DATE, DELISTING_DATE, CREATED_AT, UPDATED_AT)
SELECT 
    'TIME_SERIES_DAILY_ADJUSTED' as TABLE_NAME,
    SYMBOL_ID,
    SYMBOL,
    NAME,
    EXCHANGE,
    ASSET_TYPE,
    STATUS,
    'YES' as API_ELIGIBLE,  -- All symbols are eligible for time series
    IPO_DATE,
    DELISTING_DATE,
    CURRENT_TIMESTAMP() as CREATED_AT,
    CURRENT_TIMESTAMP() as UPDATED_AT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'LISTING_STATUS'
  AND NOT EXISTS (
      SELECT 1 FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS w2
      WHERE w2.TABLE_NAME = 'TIME_SERIES_DAILY_ADJUSTED'
        AND w2.SYMBOL_ID = ETL_WATERMARKS.SYMBOL_ID
  );

-- Show summary of created watermarks
SELECT 'TIME_SERIES_DAILY_ADJUSTED watermarks created:' as MESSAGE;

SELECT 
    EXCHANGE,
    ASSET_TYPE,
    STATUS,
    API_ELIGIBLE,
    COUNT(*) as SYMBOL_COUNT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'TIME_SERIES_DAILY_ADJUSTED'
GROUP BY EXCHANGE, ASSET_TYPE, STATUS, API_ELIGIBLE
ORDER BY EXCHANGE, ASSET_TYPE, STATUS;

-- Show total count
SELECT 
    TABLE_NAME,
    COUNT(*) as TOTAL_SYMBOLS,
    COUNT(CASE WHEN API_ELIGIBLE = 'YES' THEN 1 END) as API_ELIGIBLE_COUNT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'TIME_SERIES_DAILY_ADJUSTED'
GROUP BY TABLE_NAME;

-- ============================================================================
-- COMPANY_OVERVIEW Watermarks
-- ============================================================================
-- Only common stocks are eligible for company overview

INSERT INTO FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS 
    (TABLE_NAME, SYMBOL_ID, SYMBOL, NAME, EXCHANGE, ASSET_TYPE, STATUS, API_ELIGIBLE, 
     IPO_DATE, DELISTING_DATE, CREATED_AT, UPDATED_AT)
SELECT 
    'COMPANY_OVERVIEW' as TABLE_NAME,
    SYMBOL_ID,
    SYMBOL,
    NAME,
    EXCHANGE,
    ASSET_TYPE,
    STATUS,
    CASE 
        WHEN UPPER(ASSET_TYPE) = 'STOCK' THEN 'YES'
        ELSE 'NO'
    END as API_ELIGIBLE,
    IPO_DATE,
    DELISTING_DATE,
    CURRENT_TIMESTAMP() as CREATED_AT,
    CURRENT_TIMESTAMP() as UPDATED_AT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'LISTING_STATUS'
  AND NOT EXISTS (
      SELECT 1 FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS w2
      WHERE w2.TABLE_NAME = 'COMPANY_OVERVIEW'
        AND w2.SYMBOL_ID = ETL_WATERMARKS.SYMBOL_ID
  );

-- Show summary
SELECT 'COMPANY_OVERVIEW watermarks created:' as MESSAGE;

SELECT 
    ASSET_TYPE,
    STATUS,
    API_ELIGIBLE,
    COUNT(*) as SYMBOL_COUNT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'COMPANY_OVERVIEW'
GROUP BY ASSET_TYPE, STATUS, API_ELIGIBLE
ORDER BY ASSET_TYPE, STATUS, API_ELIGIBLE;

-- ============================================================================
-- BALANCE_SHEET Watermarks
-- ============================================================================
-- Only active common stocks are eligible for balance sheet

INSERT INTO FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS 
    (TABLE_NAME, SYMBOL_ID, SYMBOL, NAME, EXCHANGE, ASSET_TYPE, STATUS, API_ELIGIBLE, 
     IPO_DATE, DELISTING_DATE, CREATED_AT, UPDATED_AT)
SELECT 
    'BALANCE_SHEET' as TABLE_NAME,
    SYMBOL_ID,
    SYMBOL,
    NAME,
    EXCHANGE,
    ASSET_TYPE,
    STATUS,
    CASE 
        WHEN UPPER(ASSET_TYPE) = 'STOCK' AND UPPER(STATUS) = 'ACTIVE' THEN 'YES'
        ELSE 'NO'
    END as API_ELIGIBLE,
    IPO_DATE,
    DELISTING_DATE,
    CURRENT_TIMESTAMP() as CREATED_AT,
    CURRENT_TIMESTAMP() as UPDATED_AT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'LISTING_STATUS'
  AND NOT EXISTS (
      SELECT 1 FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS w2
      WHERE w2.TABLE_NAME = 'BALANCE_SHEET'
        AND w2.SYMBOL_ID = ETL_WATERMARKS.SYMBOL_ID
  );

-- Show summary
SELECT 'BALANCE_SHEET watermarks created:' as MESSAGE;

SELECT 
    ASSET_TYPE,
    STATUS,
    API_ELIGIBLE,
    COUNT(*) as SYMBOL_COUNT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'BALANCE_SHEET'
GROUP BY ASSET_TYPE, STATUS, API_ELIGIBLE
ORDER BY ASSET_TYPE, STATUS, API_ELIGIBLE;

-- ============================================================================
-- CASH_FLOW Watermarks
-- ============================================================================
-- Only active common stocks are eligible for cash flow

INSERT INTO FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS 
    (TABLE_NAME, SYMBOL_ID, SYMBOL, NAME, EXCHANGE, ASSET_TYPE, STATUS, API_ELIGIBLE, 
     IPO_DATE, DELISTING_DATE, CREATED_AT, UPDATED_AT)
SELECT 
    'CASH_FLOW' as TABLE_NAME,
    SYMBOL_ID,
    SYMBOL,
    NAME,
    EXCHANGE,
    ASSET_TYPE,
    STATUS,
    CASE 
        WHEN UPPER(ASSET_TYPE) = 'STOCK' AND UPPER(STATUS) = 'ACTIVE' THEN 'YES'
        ELSE 'NO'
    END as API_ELIGIBLE,
    IPO_DATE,
    DELISTING_DATE,
    CURRENT_TIMESTAMP() as CREATED_AT,
    CURRENT_TIMESTAMP() as UPDATED_AT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'LISTING_STATUS'
  AND NOT EXISTS (
      SELECT 1 FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS w2
      WHERE w2.TABLE_NAME = 'CASH_FLOW'
        AND w2.SYMBOL_ID = ETL_WATERMARKS.SYMBOL_ID
  );

-- Show summary
SELECT 'CASH_FLOW watermarks created:' as MESSAGE;

SELECT 
    ASSET_TYPE,
    STATUS,
    API_ELIGIBLE,
    COUNT(*) as SYMBOL_COUNT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'CASH_FLOW'
GROUP BY ASSET_TYPE, STATUS, API_ELIGIBLE
ORDER BY ASSET_TYPE, STATUS, API_ELIGIBLE;

-- ============================================================================
-- INCOME_STATEMENT Watermarks
-- ============================================================================
-- Only active common stocks are eligible for income statement

INSERT INTO FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS 
    (TABLE_NAME, SYMBOL_ID, SYMBOL, NAME, EXCHANGE, ASSET_TYPE, STATUS, API_ELIGIBLE, 
     IPO_DATE, DELISTING_DATE, CREATED_AT, UPDATED_AT)
SELECT 
    'INCOME_STATEMENT' as TABLE_NAME,
    SYMBOL_ID,
    SYMBOL,
    NAME,
    EXCHANGE,
    ASSET_TYPE,
    STATUS,
    CASE 
        WHEN UPPER(ASSET_TYPE) = 'STOCK' AND UPPER(STATUS) = 'ACTIVE' THEN 'YES'
        ELSE 'NO'
    END as API_ELIGIBLE,
    IPO_DATE,
    DELISTING_DATE,
    CURRENT_TIMESTAMP() as CREATED_AT,
    CURRENT_TIMESTAMP() as UPDATED_AT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'LISTING_STATUS'
  AND NOT EXISTS (
      SELECT 1 FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS w2
      WHERE w2.TABLE_NAME = 'INCOME_STATEMENT'
        AND w2.SYMBOL_ID = ETL_WATERMARKS.SYMBOL_ID
  );

-- Show summary
SELECT 'INCOME_STATEMENT watermarks created:' as MESSAGE;

SELECT 
    ASSET_TYPE,
    STATUS,
    API_ELIGIBLE,
    COUNT(*) as SYMBOL_COUNT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'INCOME_STATEMENT'
GROUP BY ASSET_TYPE, STATUS, API_ELIGIBLE
ORDER BY ASSET_TYPE, STATUS, API_ELIGIBLE;

-- ============================================================================
-- INSIDER_TRANSACTIONS Watermarks
-- ============================================================================
-- Only active common stocks are eligible for insider transactions

INSERT INTO FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS 
    (TABLE_NAME, SYMBOL_ID, SYMBOL, NAME, EXCHANGE, ASSET_TYPE, STATUS, API_ELIGIBLE, 
     IPO_DATE, DELISTING_DATE, CREATED_AT, UPDATED_AT)
SELECT 
    'INSIDER_TRANSACTIONS' as TABLE_NAME,
    SYMBOL_ID,
    SYMBOL,
    NAME,
    EXCHANGE,
    ASSET_TYPE,
    STATUS,
    CASE 
        WHEN UPPER(ASSET_TYPE) = 'STOCK' AND UPPER(STATUS) = 'ACTIVE' THEN 'YES'
        ELSE 'NO'
    END as API_ELIGIBLE,
    IPO_DATE,
    DELISTING_DATE,
    CURRENT_TIMESTAMP() as CREATED_AT,
    CURRENT_TIMESTAMP() as UPDATED_AT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'LISTING_STATUS'
  AND NOT EXISTS (
      SELECT 1 FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS w2
      WHERE w2.TABLE_NAME = 'INSIDER_TRANSACTIONS'
        AND w2.SYMBOL_ID = ETL_WATERMARKS.SYMBOL_ID
  );

-- Show summary
SELECT 'INSIDER_TRANSACTIONS watermarks created:' as MESSAGE;

SELECT 
    ASSET_TYPE,
    STATUS,
    API_ELIGIBLE,
    COUNT(*) as SYMBOL_COUNT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'INSIDER_TRANSACTIONS'
GROUP BY ASSET_TYPE, STATUS, API_ELIGIBLE
ORDER BY ASSET_TYPE, STATUS, API_ELIGIBLE;

-- ============================================================================
-- EARNINGS_CALL_TRANSCRIPT Watermarks
-- ============================================================================
-- Only active common stocks are eligible for earnings call transcripts

INSERT INTO FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS 
    (TABLE_NAME, SYMBOL_ID, SYMBOL, NAME, EXCHANGE, ASSET_TYPE, STATUS, API_ELIGIBLE, 
     IPO_DATE, DELISTING_DATE, CREATED_AT, UPDATED_AT)
SELECT 
    'EARNINGS_CALL_TRANSCRIPT' as TABLE_NAME,
    SYMBOL_ID,
    SYMBOL,
    NAME,
    EXCHANGE,
    ASSET_TYPE,
    STATUS,
    CASE 
        WHEN UPPER(ASSET_TYPE) = 'STOCK' AND UPPER(STATUS) = 'ACTIVE' THEN 'YES'
        ELSE 'NO'
    END as API_ELIGIBLE,
    IPO_DATE,
    DELISTING_DATE,
    CURRENT_TIMESTAMP() as CREATED_AT,
    CURRENT_TIMESTAMP() as UPDATED_AT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'LISTING_STATUS'
  AND NOT EXISTS (
      SELECT 1 FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS w2
      WHERE w2.TABLE_NAME = 'EARNINGS_CALL_TRANSCRIPT'
        AND w2.SYMBOL_ID = ETL_WATERMARKS.SYMBOL_ID
  );

-- Show summary
SELECT 'EARNINGS_CALL_TRANSCRIPT watermarks created:' as MESSAGE;

SELECT 
    ASSET_TYPE,
    STATUS,
    API_ELIGIBLE,
    COUNT(*) as SYMBOL_COUNT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'EARNINGS_CALL_TRANSCRIPT'
GROUP BY ASSET_TYPE, STATUS, API_ELIGIBLE
ORDER BY ASSET_TYPE, STATUS, API_ELIGIBLE;

-- ============================================================================
-- Final Summary - All Data Sources
-- ============================================================================

SELECT 'Final Summary - All Data Sources:' as MESSAGE;

SELECT 
    TABLE_NAME,
    COUNT(*) as TOTAL_SYMBOLS,
    COUNT(CASE WHEN API_ELIGIBLE = 'YES' THEN 1 END) as API_ELIGIBLE,
    COUNT(CASE WHEN API_ELIGIBLE = 'NO' THEN 1 END) as NOT_ELIGIBLE,
    ROUND(COUNT(CASE WHEN API_ELIGIBLE = 'YES' THEN 1 END) * 100.0 / COUNT(*), 2) as ELIGIBLE_PCT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;

SELECT '✅ All data source watermarks created successfully!' as COMPLETION_STATUS;
