-- Check if ETL_WATERMARKS table exists and view its structure
USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;
USE WAREHOUSE FIN_TRADE_WH;
USE ROLE ETL_ROLE;

-- 1) Check if table exists
SELECT 'ETL_WATERMARKS table exists' as status
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'RAW' 
  AND TABLE_NAME = 'ETL_WATERMARKS'
  AND TABLE_CATALOG = 'FIN_TRADE_EXTRACT';

-- 2) Show table structure if it exists
DESCRIBE TABLE FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS;

-- 3) Count records by table type
SELECT 
    TABLE_NAME,
    COUNT(*) as record_count,
    MIN(CREATED_AT) as oldest_record,
    MAX(UPDATED_AT) as newest_record
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS 
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;

-- 4) Sample records
SELECT TOP 10 *
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS 
ORDER BY CREATED_AT DESC;