-- Cleanup Bad COMPANY_OVERVIEW Watermarks
-- These were created with Python hash() instead of Snowflake HASH()
-- This causes SYMBOL_ID mismatches with other watermarks

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;
USE WAREHOUSE FIN_TRADE_WH;
USE ROLE ACCOUNTADMIN;

-- Check how many bad records we have
SELECT 'Bad COMPANY_OVERVIEW watermarks to delete:' as MESSAGE;
SELECT COUNT(*) as bad_records
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'COMPANY_OVERVIEW'
  AND SYMBOL_ID NOT IN (
    SELECT SYMBOL_ID 
    FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS 
    WHERE TABLE_NAME = 'LISTING_STATUS'
  );

-- Show example of mismatches
SELECT 'Example mismatch for symbol AA:' as MESSAGE;
SELECT 
    TABLE_NAME,
    SYMBOL_ID,
    SYMBOL,
    NAME,
    LAST_FISCAL_DATE,
    CREATED_AT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE SYMBOL = 'AA'
ORDER BY TABLE_NAME;

-- Delete bad COMPANY_OVERVIEW watermarks
DELETE FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'COMPANY_OVERVIEW'
  AND SYMBOL_ID NOT IN (
    SELECT SYMBOL_ID 
    FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS 
    WHERE TABLE_NAME = 'LISTING_STATUS'
  );

-- Verify deletion
SELECT 'After cleanup:' as MESSAGE;
SELECT COUNT(*) as remaining_company_overview_records
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'COMPANY_OVERVIEW';

-- Verify AA now has consistent SYMBOL_IDs
SELECT 'Symbol AA after cleanup:' as MESSAGE;
SELECT 
    TABLE_NAME,
    SYMBOL_ID,
    SYMBOL,
    NAME
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE SYMBOL = 'AA'
ORDER BY TABLE_NAME;
