USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;
USE WAREHOUSE FIN_TRADE_WH;

-- Manually load 2025-09-29 overview CSVs directly into the final table using table column order
COPY INTO RAW.OVERVIEW
FROM @OVERVIEW_STAGE
PATTERN = '.*overview_20250929.*\\.csv'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS records_after FROM RAW.OVERVIEW;
SELECT * FROM RAW.OVERVIEW ORDER BY CREATED_AT DESC NULLS LAST LIMIT 50;