-- Delete All COMPANY_OVERVIEW Watermarks
-- These were created before running the COMPANY_OVERVIEW ETL
-- They have incorrect SYMBOL_ID values (Python hash vs Snowflake HASH)

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;
USE WAREHOUSE FIN_TRADE_WH;
USE ROLE ACCOUNTADMIN;

-- Step 1: Check how many COMPANY_OVERVIEW watermarks exist
SELECT 'Current COMPANY_OVERVIEW watermarks:' as MESSAGE;
SELECT COUNT(*) as company_overview_count
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'COMPANY_OVERVIEW';

-- Step 2: Show sample records to verify
SELECT 'Sample COMPANY_OVERVIEW watermarks:' as MESSAGE;
SELECT 
    TABLE_NAME,
    SYMBOL_ID,
    SYMBOL,
    NAME,
    EXCHANGE,
    ASSET_TYPE,
    STATUS,
    API_ELIGIBLE,
    LAST_FISCAL_DATE,
    LAST_SUCCESSFUL_RUN,
    CREATED_AT,
    UPDATED_AT
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'COMPANY_OVERVIEW'
ORDER BY SYMBOL
LIMIT 10;

-- Step 3: Check total watermarks before deletion
SELECT 'Total watermarks before deletion:' as MESSAGE;
SELECT 
    TABLE_NAME,
    COUNT(*) as record_count
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;

-- Step 4: DELETE all COMPANY_OVERVIEW watermarks
DELETE FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'COMPANY_OVERVIEW';

-- Step 5: Verify deletion
SELECT 'Deletion complete. Remaining watermarks:' as MESSAGE;
SELECT 
    TABLE_NAME,
    COUNT(*) as record_count
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;

-- Step 6: Confirm COMPANY_OVERVIEW is gone
SELECT 'COMPANY_OVERVIEW watermarks remaining:' as MESSAGE;
SELECT COUNT(*) as company_overview_count
FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
WHERE TABLE_NAME = 'COMPANY_OVERVIEW';

-- Expected result: 0 records
