-- Full-load MERGE for overview data (dedup + watermark)
-- Set LOAD_DATE to the file date (YYYY-MM-DD); BATCH_ID will be derived as FULL_LOAD_yyyymmdd

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;
USE WAREHOUSE FIN_TRADE_WH;

-- Parameters
SET LOAD_DATE = '2025-09-29';
SET BATCH_ID = 'FULL_LOAD_' || REPLACE($LOAD_DATE, '-', '');
SET SOURCE_FILE_NAME = 'full_load';

-- 1) Staging shaped like CSV
CREATE OR REPLACE TABLE RAW.OVERVIEW_STAGING (
  SYMBOL_ID VARCHAR(50),
  SYMBOL VARCHAR(20),
  ASSET_TYPE VARCHAR(50),
  NAME VARCHAR(500),
  DESCRIPTION TEXT,
  CIK VARCHAR(20),
  EXCHANGE VARCHAR(50),
  CURRENCY VARCHAR(10),
  COUNTRY VARCHAR(100),
  SECTOR VARCHAR(100),
  INDUSTRY VARCHAR(200),
  ADDRESS TEXT,
  OFFICIAL_SITE VARCHAR(500),
  FISCAL_YEAR_END VARCHAR(50),
  MARKET_CAPITALIZATION VARCHAR(50),
  EBITDA VARCHAR(50),
  PE_RATIO VARCHAR(50),
  PEG_RATIO VARCHAR(50),
  BOOK_VALUE VARCHAR(50),
  DIVIDEND_PER_SHARE VARCHAR(50),
  DIVIDEND_YIELD VARCHAR(50),
  EPS VARCHAR(50),
  REVENUE_PER_SHARE_TTM VARCHAR(50),
  PROFIT_MARGIN VARCHAR(50),
  OPERATING_MARGIN_TTM VARCHAR(50),
  RETURN_ON_ASSETS_TTM VARCHAR(50),
  RETURN_ON_EQUITY_TTM VARCHAR(50),
  REVENUE_TTM VARCHAR(50),
  GROSS_PROFIT_TTM VARCHAR(50),
  DILUTED_EPS_TTM VARCHAR(50),
  QUARTERLY_EARNINGS_GROWTH_YOY VARCHAR(50),
  QUARTERLY_REVENUE_GROWTH_YOY VARCHAR(50),
  ANALYST_TARGET_PRICE VARCHAR(50),
  TRAILING_PE VARCHAR(50),
  FORWARD_PE VARCHAR(50),
  PRICE_TO_SALES_RATIO_TTM VARCHAR(50),
  PRICE_TO_BOOK_RATIO VARCHAR(50),
  EV_TO_REVENUE VARCHAR(50),
  EV_TO_EBITDA VARCHAR(50),
  BETA VARCHAR(50),
  WEEK_52_HIGH VARCHAR(50),
  WEEK_52_LOW VARCHAR(50),
  DAY_50_MOVING_AVERAGE VARCHAR(50),
  DAY_200_MOVING_AVERAGE VARCHAR(50),
  SHARES_OUTSTANDING VARCHAR(50),
  DIVIDEND_DATE VARCHAR(50),
  EX_DIVIDEND_DATE VARCHAR(50),
  API_RESPONSE_STATUS VARCHAR(50),
  CREATED_AT VARCHAR(50),
  UPDATED_AT VARCHAR(50)
);

-- 2) Load only files for LOAD_DATE
COPY INTO RAW.OVERVIEW_STAGING
FROM @OVERVIEW_STAGE
PATTERN = '.*overview_' || REPLACE($LOAD_DATE, '-', '') || '.*\\.csv'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- 3) MERGE with dedup by SYMBOL and batch watermark
MERGE INTO RAW.OVERVIEW AS tgt
USING (
  WITH stg AS (
    SELECT
      *,
      TRY_TO_TIMESTAMP_NTZ(CREATED_AT) AS CREATED_AT_TS,
      TRY_TO_TIMESTAMP_NTZ(UPDATED_AT) AS UPDATED_AT_TS,
      ROW_NUMBER() OVER (
        PARTITION BY SYMBOL
        ORDER BY TRY_TO_TIMESTAMP_NTZ(UPDATED_AT) DESC NULLS LAST,
                 TRY_TO_TIMESTAMP_NTZ(CREATED_AT) DESC NULLS LAST
      ) AS rn
    FROM RAW.OVERVIEW_STAGING
    WHERE SYMBOL IS NOT NULL AND TRIM(SYMBOL) <> ''
  )
  SELECT
    SYMBOL_ID,
    SYMBOL,
    ASSET_TYPE,
    NAME,
    DESCRIPTION,
    CIK,
    EXCHANGE,
    CURRENCY,
    COUNTRY,
    SECTOR,
    INDUSTRY,
    ADDRESS,
    OFFICIAL_SITE,
    FISCAL_YEAR_END,
    API_RESPONSE_STATUS,
    CREATED_AT_TS,
    UPDATED_AT_TS
  FROM stg
  WHERE rn = 1
) AS src
ON tgt.SYMBOL = src.SYMBOL
WHEN MATCHED THEN UPDATE SET
  tgt.SYMBOL_ID = src.SYMBOL_ID,
  tgt.ASSET_TYPE = src.ASSET_TYPE,
  tgt.NAME = src.NAME,
  tgt.DESCRIPTION = src.DESCRIPTION,
  tgt.CIK = src.CIK,
  tgt.EXCHANGE = src.EXCHANGE,
  tgt.CURRENCY = src.CURRENCY,
  tgt.COUNTRY = src.COUNTRY,
  tgt.SECTOR = src.SECTOR,
  tgt.INDUSTRY = src.INDUSTRY,
  tgt.ADDRESS = src.ADDRESS,
  tgt.OFFICIALSITE = src.OFFICIAL_SITE,
  tgt.FISCALYEAREND = src.FISCAL_YEAR_END,
  tgt.STATUS = src.API_RESPONSE_STATUS,
  tgt.CREATED_AT = src.CREATED_AT_TS,
  tgt.UPDATED_AT = src.UPDATED_AT_TS,
  tgt.BATCH_ID = $BATCH_ID,
  tgt.SOURCE_FILE_NAME = $SOURCE_FILE_NAME
WHEN NOT MATCHED THEN INSERT (
  SYMBOL_ID, SYMBOL, ASSET_TYPE, NAME, DESCRIPTION, CIK, EXCHANGE,
  CURRENCY, COUNTRY, SECTOR, INDUSTRY, ADDRESS, OFFICIALSITE,
  FISCALYEAREND, STATUS, CREATED_AT, UPDATED_AT,
  BATCH_ID, SOURCE_FILE_NAME
) VALUES (
  src.SYMBOL_ID, src.SYMBOL, src.ASSET_TYPE, src.NAME, src.DESCRIPTION, src.CIK, src.EXCHANGE,
  src.CURRENCY, src.COUNTRY, src.SECTOR, src.INDUSTRY, src.ADDRESS, src.OFFICIAL_SITE,
  src.FISCAL_YEAR_END, src.API_RESPONSE_STATUS, src.CREATED_AT_TS, src.UPDATED_AT_TS,
  $BATCH_ID, $SOURCE_FILE_NAME
);

-- 4) Verify
SELECT COUNT(*) AS total_after FROM RAW.OVERVIEW;
SELECT COUNT(*) AS batch_count FROM RAW.OVERVIEW WHERE BATCH_ID = $BATCH_ID;
SELECT * FROM RAW.OVERVIEW WHERE BATCH_ID = $BATCH_ID ORDER BY CREATED_AT DESC NULLS LAST LIMIT 50;
