-- Load ETF Profile Data from S3 to Snowflake
-- Source: Alpha Vantage ETF_PROFILE API endpoint
-- Destination: FIN_TRADE_EXTRACT.RAW.ETF_PROFILE

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;
USE WAREHOUSE FIN_TRADE_WH;
USE ROLE ETL_ROLE;

CREATE OR REPLACE STAGE FIN_TRADE_EXTRACT.RAW.ETF_PROFILE_STAGE
  URL='s3://fin-trade-craft-landing/etf_profile/'
  STORAGE_INTEGRATION = FIN_TRADE_S3_INTEGRATION
  FILE_FORMAT = (TYPE = 'JSON');

-- Create target table if not exists
CREATE TABLE IF NOT EXISTS FIN_TRADE_EXTRACT.RAW.ETF_PROFILE (
    SYMBOL VARCHAR(20) PRIMARY KEY,
    PROFILE_DATA VARIANT,
    LOAD_DATE DATE DEFAULT CURRENT_DATE()
);

-- Load data from S3
COPY INTO FIN_TRADE_EXTRACT.RAW.ETF_PROFILE
FROM (
    SELECT $1:Symbol::STRING AS SYMBOL, $1 AS PROFILE_DATA, CURRENT_DATE() AS LOAD_DATE
    FROM @FIN_TRADE_EXTRACT.RAW.ETF_PROFILE_STAGE
)
FILE_FORMAT = (TYPE = 'JSON');

-- Show load results
SELECT COUNT(*) AS total_records FROM FIN_TRADE_EXTRACT.RAW.ETF_PROFILE;
