-- DEBUG VERSION: Load company overview CSV files to see actual structure
-- This version focuses on getting ANY data loaded first, then we can optimize

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;
USE WAREHOUSE FIN_TRADE_WH;
USE ROLE ACCOUNTADMIN;

-- 1) Create stage if needed
CREATE STAGE IF NOT EXISTS FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGE
  URL='s3://fin-trade-craft-landing/company_overview/'
  STORAGE_INTEGRATION = FIN_TRADE_S3_INTEGRATION;

-- 2) Create main COMPANY_OVERVIEW table with proper data types
CREATE TABLE IF NOT EXISTS FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW (
  SYMBOL_ID NUMBER(38,0),
  SYMBOL VARCHAR(20),
  ASSET_TYPE VARCHAR(50),
  NAME VARCHAR(500),
  DESCRIPTION TEXT,
  CIK VARCHAR(20),
  EXCHANGE VARCHAR(50),
  CURRENCY VARCHAR(10),
  COUNTRY VARCHAR(100),
  SECTOR VARCHAR(100),
  INDUSTRY VARCHAR(200),
  ADDRESS TEXT,
  OFFICIAL_SITE VARCHAR(500),
  FISCAL_YEAR_END VARCHAR(50),
  MARKET_CAPITALIZATION NUMBER,
  EBITDA NUMBER,
  PE_RATIO NUMBER,
  PEG_RATIO NUMBER,
  BOOK_VALUE NUMBER,
  DIVIDEND_PER_SHARE NUMBER,
  DIVIDEND_YIELD NUMBER,
  EPS NUMBER,
  REVENUE_PER_SHARE_TTM NUMBER,
  PROFIT_MARGIN NUMBER,
  OPERATING_MARGIN_TTM NUMBER,
  RETURN_ON_ASSETS_TTM NUMBER,
  RETURN_ON_EQUITY_TTM NUMBER,
  REVENUE_TTM NUMBER,
  GROSS_PROFIT_TTM NUMBER,
  DILUTED_EPS_TTM NUMBER,
  QUARTERLY_EARNINGS_GROWTH_YOY NUMBER,
  QUARTERLY_REVENUE_GROWTH_YOY NUMBER,
  ANALYST_TARGET_PRICE NUMBER,
  TRAILING_PE NUMBER,
  FORWARD_PE NUMBER,
  PRICE_TO_SALES_RATIO_TTM NUMBER,
  PRICE_TO_BOOK_RATIO NUMBER,
  EV_TO_REVENUE NUMBER,
  EV_TO_EBITDA NUMBER,
  BETA NUMBER,
  WEEK_52_HIGH NUMBER,
  WEEK_52_LOW NUMBER,
  DAY_50_MOVING_AVERAGE NUMBER,
  DAY_200_MOVING_AVERAGE NUMBER,
  SHARES_OUTSTANDING NUMBER,
  DIVIDEND_DATE DATE,
  EX_DIVIDEND_DATE DATE,
  LATEST_QUARTER DATE,
  PROCESSED_DATE DATE,
  LOAD_DATE VARCHAR(50),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 3) Drop and recreate staging table to match exact Alpha Vantage API field names
DROP TABLE IF EXISTS FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING;

CREATE TRANSIENT TABLE FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING (
  -- Exact Alpha Vantage API field names (case-sensitive)
  Symbol VARCHAR(500),
  AssetType VARCHAR(500),
  Name VARCHAR(500),
  Description VARCHAR(2000),
  CIK VARCHAR(500),
  Exchange VARCHAR(500),
  Currency VARCHAR(500),
  Country VARCHAR(500),
  Sector VARCHAR(500),
  Industry VARCHAR(500),
  Address VARCHAR(2000),
  OfficialSite VARCHAR(500),
  FiscalYearEnd VARCHAR(500),
  LatestQuarter VARCHAR(500),
  MarketCapitalization VARCHAR(500),
  EBITDA VARCHAR(500),
  PERatio VARCHAR(500),
  PEGRatio VARCHAR(500),
  BookValue VARCHAR(500),
  DividendPerShare VARCHAR(500),
  DividendYield VARCHAR(500),
  EPS VARCHAR(500),
  RevenuePerShareTTM VARCHAR(500),
  ProfitMargin VARCHAR(500),
  OperatingMarginTTM VARCHAR(500),
  ReturnOnAssetsTTM VARCHAR(500),
  ReturnOnEquityTTM VARCHAR(500),
  RevenueTTM VARCHAR(500),
  GrossProfitTTM VARCHAR(500),
  DilutedEPSTTM VARCHAR(500),
  QuarterlyEarningsGrowthYOY VARCHAR(500),
  QuarterlyRevenueGrowthYOY VARCHAR(500),
  AnalystTargetPrice VARCHAR(500),
  AnalystRatingStrongBuy VARCHAR(500),
  AnalystRatingBuy VARCHAR(500),
  AnalystRatingHold VARCHAR(500),
  AnalystRatingSell VARCHAR(500),
  AnalystRatingStrongSell VARCHAR(500),
  TrailingPE VARCHAR(500),
  ForwardPE VARCHAR(500),
  PriceToSalesRatioTTM VARCHAR(500),
  PriceToBookRatio VARCHAR(500),
  EVToRevenue VARCHAR(500),
  EVToEBITDA VARCHAR(500),
  Beta VARCHAR(500),
  "52WeekHigh" VARCHAR(500),
  "52WeekLow" VARCHAR(500),
  "50DayMovingAverage" VARCHAR(500),
  "200DayMovingAverage" VARCHAR(500),
  SharesOutstanding VARCHAR(500),
  SharesFloat VARCHAR(500),
  PercentInsiders VARCHAR(500),
  PercentInstitutions VARCHAR(500),
  DividendDate VARCHAR(500),
  ExDividendDate VARCHAR(500),
  
  -- Processing metadata (added by Python script)
  SYMBOL_ID VARCHAR(500),
  PROCESSED_DATE VARCHAR(500),
  LOAD_DATE VARCHAR(500),
  
  -- File tracking (automatically added by Snowflake COPY command)
  source_file VARCHAR(500) DEFAULT NULL
);

-- Debug: Check what files are in the stage
SELECT 'Files in S3 stage:' as MESSAGE;
LIST @COMPANY_OVERVIEW_STAGE;

-- Debug: Check if RAW_CSV_FORMAT exists
SHOW FILE FORMATS LIKE 'RAW_CSV_FORMAT';

-- Load CSV files using MATCH_BY_COLUMN_NAME to handle different column orders
COPY INTO FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING 
FROM @COMPANY_OVERVIEW_STAGE
FILE_FORMAT = (
  TYPE = 'CSV',
  FIELD_DELIMITER = ',',
  RECORD_DELIMITER = '\n',
  SKIP_HEADER = 1,
  FIELD_OPTIONALLY_ENCLOSED_BY = '"',
  ESCAPE = '\\',
  NULL_IF = ('', 'NULL', 'null', 'None'),
  EMPTY_FIELD_AS_NULL = TRUE,
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = 'overview_.*\\.csv'
ON_ERROR = CONTINUE;

-- Debug: Check load results
SELECT 'Load Results:' as MESSAGE;

SELECT 
    'Total rows loaded:' as METRIC,
    COUNT(*) as VALUE
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING;

SELECT 
    'Files processed:' as METRIC,
    COUNT(DISTINCT source_file) as VALUE
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING;

-- Show files and row counts
SELECT 
    source_file,
    COUNT(*) as rows_per_file
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING 
GROUP BY source_file
ORDER BY source_file;

-- Show sample data with proper column names
SELECT 'Core company information:' as MESSAGE;
SELECT 
    Symbol, Name, Exchange, AssetType, Country, Sector, Industry,
    source_file
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING 
LIMIT 3;

-- Show key fiscal fields you mentioned
SELECT 'Key fiscal data fields:' as MESSAGE;
SELECT 
    Symbol, FiscalYearEnd, LatestQuarter, MarketCapitalization,
    source_file
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING 
LIMIT 3;

-- Show financial metrics
SELECT 'Financial metrics sample:' as MESSAGE;
SELECT 
    Symbol, PERatio, EPS, ProfitMargin, Beta, 
    "52WeekHigh", "52WeekLow",
    source_file
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING 
LIMIT 3;

-- Show processing metadata
SELECT 'Processing metadata:' as MESSAGE;
SELECT 
    Symbol, SYMBOL_ID, PROCESSED_DATE, LOAD_DATE,
    source_file
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING 
LIMIT 3;

-- Check for data completeness in key fields
SELECT 'Data completeness analysis:' as MESSAGE;
SELECT 
    COUNT(*) as total_rows,
    COUNT(Symbol) as symbols_with_data,
    COUNT(FiscalYearEnd) as fiscal_year_end_populated,
    COUNT(LatestQuarter) as latest_quarter_populated,
    COUNT(MarketCapitalization) as market_cap_populated,
    COUNT(Name) as company_name_populated
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING;

-- NO DELETE STATEMENTS - KEEP ALL DATA FOR DEBUGGING

-- Transfer data from staging to main table with proper type conversions
INSERT INTO FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW (
  SYMBOL_ID, SYMBOL, ASSET_TYPE, NAME, DESCRIPTION, CIK, EXCHANGE, CURRENCY, COUNTRY,
  SECTOR, INDUSTRY, ADDRESS, OFFICIAL_SITE, FISCAL_YEAR_END, MARKET_CAPITALIZATION,
  EBITDA, PE_RATIO, PEG_RATIO, BOOK_VALUE, DIVIDEND_PER_SHARE, DIVIDEND_YIELD, EPS,
  REVENUE_PER_SHARE_TTM, PROFIT_MARGIN, OPERATING_MARGIN_TTM, RETURN_ON_ASSETS_TTM,
  RETURN_ON_EQUITY_TTM, REVENUE_TTM, GROSS_PROFIT_TTM, DILUTED_EPS_TTM,
  QUARTERLY_EARNINGS_GROWTH_YOY, QUARTERLY_REVENUE_GROWTH_YOY, ANALYST_TARGET_PRICE,
  TRAILING_PE, FORWARD_PE, PRICE_TO_SALES_RATIO_TTM, PRICE_TO_BOOK_RATIO,
  EV_TO_REVENUE, EV_TO_EBITDA, BETA, WEEK_52_HIGH, WEEK_52_LOW,
  DAY_50_MOVING_AVERAGE, DAY_200_MOVING_AVERAGE, SHARES_OUTSTANDING,
  DIVIDEND_DATE, EX_DIVIDEND_DATE, LATEST_QUARTER, PROCESSED_DATE, LOAD_DATE, UPDATED_AT
)
SELECT 
  TRY_TO_NUMBER(SYMBOL_ID) as SYMBOL_ID,
  Symbol,
  AssetType as ASSET_TYPE,
  Name,
  Description,
  CIK,
  Exchange,
  Currency,
  Country,
  Sector,
  Industry,
  Address,
  OfficialSite as OFFICIAL_SITE,
  FiscalYearEnd as FISCAL_YEAR_END,
  TRY_TO_NUMBER(MarketCapitalization) as MARKET_CAPITALIZATION,
  TRY_TO_NUMBER(EBITDA) as EBITDA,
  TRY_TO_NUMBER(PERatio) as PE_RATIO,
  TRY_TO_NUMBER(PEGRatio) as PEG_RATIO,
  TRY_TO_NUMBER(BookValue) as BOOK_VALUE,
  TRY_TO_NUMBER(DividendPerShare) as DIVIDEND_PER_SHARE,
  TRY_TO_NUMBER(DividendYield) as DIVIDEND_YIELD,
  TRY_TO_NUMBER(EPS) as EPS,
  TRY_TO_NUMBER(RevenuePerShareTTM) as REVENUE_PER_SHARE_TTM,
  TRY_TO_NUMBER(ProfitMargin) as PROFIT_MARGIN,
  TRY_TO_NUMBER(OperatingMarginTTM) as OPERATING_MARGIN_TTM,
  TRY_TO_NUMBER(ReturnOnAssetsTTM) as RETURN_ON_ASSETS_TTM,
  TRY_TO_NUMBER(ReturnOnEquityTTM) as RETURN_ON_EQUITY_TTM,
  TRY_TO_NUMBER(RevenueTTM) as REVENUE_TTM,
  TRY_TO_NUMBER(GrossProfitTTM) as GROSS_PROFIT_TTM,
  TRY_TO_NUMBER(DilutedEPSTTM) as DILUTED_EPS_TTM,
  TRY_TO_NUMBER(QuarterlyEarningsGrowthYOY) as QUARTERLY_EARNINGS_GROWTH_YOY,
  TRY_TO_NUMBER(QuarterlyRevenueGrowthYOY) as QUARTERLY_REVENUE_GROWTH_YOY,
  TRY_TO_NUMBER(AnalystTargetPrice) as ANALYST_TARGET_PRICE,
  TRY_TO_NUMBER(TrailingPE) as TRAILING_PE,
  TRY_TO_NUMBER(ForwardPE) as FORWARD_PE,
  TRY_TO_NUMBER(PriceToSalesRatioTTM) as PRICE_TO_SALES_RATIO_TTM,
  TRY_TO_NUMBER(PriceToBookRatio) as PRICE_TO_BOOK_RATIO,
  TRY_TO_NUMBER(EVToRevenue) as EV_TO_REVENUE,
  TRY_TO_NUMBER(EVToEBITDA) as EV_TO_EBITDA,
  TRY_TO_NUMBER(Beta) as BETA,
  TRY_TO_NUMBER("52WeekHigh") as WEEK_52_HIGH,
  TRY_TO_NUMBER("52WeekLow") as WEEK_52_LOW,
  TRY_TO_NUMBER("50DayMovingAverage") as DAY_50_MOVING_AVERAGE,
  TRY_TO_NUMBER("200DayMovingAverage") as DAY_200_MOVING_AVERAGE,
  TRY_TO_NUMBER(SharesOutstanding) as SHARES_OUTSTANDING,
  TRY_TO_DATE(DividendDate, 'YYYY-MM-DD') as DIVIDEND_DATE,
  TRY_TO_DATE(ExDividendDate, 'YYYY-MM-DD') as EX_DIVIDEND_DATE,
  TRY_TO_DATE(LatestQuarter, 'YYYY-MM-DD') as LATEST_QUARTER,
  TRY_TO_DATE(PROCESSED_DATE, 'YYYY-MM-DD') as PROCESSED_DATE,
  LOAD_DATE,
  CURRENT_TIMESTAMP() as UPDATED_AT
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING
WHERE Symbol IS NOT NULL AND Symbol != '' AND Symbol != 'Symbol';

-- Show final results
SELECT 'Data transfer completed!' as MESSAGE;

SELECT 
    'Records in staging table:' as METRIC,
    COUNT(*) as VALUE
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING;

SELECT 
    'Records in main COMPANY_OVERVIEW table:' as METRIC,
    COUNT(*) as VALUE
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW;

-- Show sample records in main table
SELECT 'Sample records in main table:' as MESSAGE;
SELECT 
    SYMBOL, FISCAL_YEAR_END, LATEST_QUARTER, MARKET_CAPITALIZATION, UPDATED_AT
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW
ORDER BY SYMBOL
LIMIT 5;

SELECT 'Debug staging table created successfully! Check the output above to understand the CSV structure.' as COMPLETION_MESSAGE;

-- Do NOT drop the staging table
SELECT 'Staging table preserved for debugging' as PRESERVATION_MESSAGE;