-- Load/merge Alpha Vantage COMPANY_OVERVIEW from S3 into RAW.COMPANY_OVERVIEW
-- Automatically processes all CSV files in the company_overview/ prefix

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;
USE WAREHOUSE FIN_TRADE_WH;
USE ROLE ACCOUNTADMIN;

-- 1) Create stage if needed
CREATE STAGE IF NOT EXISTS FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGE
  URL='s3://fin-trade-craft-landing/company_overview/'
  STORAGE_INTEGRATION = FIN_TRADE_S3_INTEGRATION;

-- 2) Create main table if needed
CREATE TABLE IF NOT EXISTS FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW (
  SYMBOL_ID NUMBER(38,0),
  SYMBOL VARCHAR(20),
  ASSET_TYPE VARCHAR(50),
  NAME VARCHAR(500),
  DESCRIPTION TEXT,
  CIK VARCHAR(20),
  EXCHANGE VARCHAR(50),
  CURRENCY VARCHAR(10),
  COUNTRY VARCHAR(100),
  SECTOR VARCHAR(100),
  INDUSTRY VARCHAR(200),
  ADDRESS TEXT,
  OFFICIAL_SITE VARCHAR(500),
  FISCAL_YEAR_END VARCHAR(50),
  MARKET_CAPITALIZATION NUMBER,
  EBITDA NUMBER,
  PE_RATIO NUMBER,
  PEG_RATIO NUMBER,
  BOOK_VALUE NUMBER,
  DIVIDEND_PER_SHARE NUMBER,
  DIVIDEND_YIELD NUMBER,
  EPS NUMBER,
  REVENUE_PER_SHARE_TTM NUMBER,
  PROFIT_MARGIN NUMBER,
  OPERATING_MARGIN_TTM NUMBER,
  RETURN_ON_ASSETS_TTM NUMBER,
  RETURN_ON_EQUITY_TTM NUMBER,
  REVENUE_TTM NUMBER,
  GROSS_PROFIT_TTM NUMBER,
  DILUTED_EPS_TTM NUMBER,
  QUARTERLY_EARNINGS_GROWTH_YOY NUMBER,
  QUARTERLY_REVENUE_GROWTH_YOY NUMBER,
  ANALYST_TARGET_PRICE NUMBER,
  TRAILING_PE NUMBER,
  FORWARD_PE NUMBER,
  PRICE_TO_SALES_RATIO_TTM NUMBER,
  PRICE_TO_BOOK_RATIO NUMBER,
  EV_TO_REVENUE NUMBER,
  EV_TO_EBITDA NUMBER,
  BETA NUMBER,
  WEEK_52_HIGH NUMBER,
  WEEK_52_LOW NUMBER,
  DAY_50_MOVING_AVERAGE NUMBER,
  DAY_200_MOVING_AVERAGE NUMBER,
  SHARES_OUTSTANDING NUMBER,
  DIVIDEND_DATE DATE,
  EX_DIVIDEND_DATE DATE,
  LATEST_QUARTER DATE,
  PROCESSED_DATE DATE,
  LOAD_DATE VARCHAR(50),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 3) Create simple staging table like listing status - capture any CSV columns
CREATE OR REPLACE TRANSIENT TABLE FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING (
  col1 VARCHAR,
  col2 VARCHAR,
  col3 VARCHAR,
  col4 VARCHAR,
  col5 VARCHAR,
  col6 VARCHAR,
  col7 VARCHAR,
  col8 VARCHAR,
  col9 VARCHAR,
  col10 VARCHAR,
  col11 VARCHAR,
  col12 VARCHAR,
  col13 VARCHAR,
  col14 VARCHAR,
  col15 VARCHAR,
  col16 VARCHAR,
  col17 VARCHAR,
  col18 VARCHAR,
  col19 VARCHAR,
  col20 VARCHAR,
  col21 VARCHAR,
  col22 VARCHAR,
  col23 VARCHAR,
  col24 VARCHAR,
  col25 VARCHAR,
  col26 VARCHAR,
  col27 VARCHAR,
  col28 VARCHAR,
  col29 VARCHAR,
  col30 VARCHAR,
  col31 VARCHAR,
  col32 VARCHAR,
  col33 VARCHAR,
  col34 VARCHAR,
  col35 VARCHAR,
  col36 VARCHAR,
  col37 VARCHAR,
  col38 VARCHAR,
  col39 VARCHAR,
  col40 VARCHAR,
  col41 VARCHAR,
  col42 VARCHAR,
  col43 VARCHAR,
  col44 VARCHAR,
  col45 VARCHAR,
  col46 VARCHAR,
  col47 VARCHAR,
  col48 VARCHAR,
  col49 VARCHAR,
  col50 VARCHAR,
  col51 VARCHAR,
  col52 VARCHAR,
  col53 VARCHAR,
  col54 VARCHAR,
  col55 VARCHAR,
  col56 VARCHAR,
  col57 VARCHAR,
  col58 VARCHAR,
  col59 VARCHAR,
  col60 VARCHAR,
  source_file VARCHAR
);

-- Debug: Check what files are in the stage
LIST @COMPANY_OVERVIEW_STAGE;

-- Load ALL CSV files using same pattern as listing status
COPY INTO FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING 
FROM (
  SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, METADATA$FILENAME
  FROM @COMPANY_OVERVIEW_STAGE
)
FILE_FORMAT = (FORMAT_NAME = FIN_TRADE_EXTRACT.RAW.RAW_CSV_FORMAT)
PATTERN = 'overview_.*\\.csv'
ON_ERROR = CONTINUE;

-- Debug: Check how many rows were loaded from each file
SELECT 
    source_file,
    COUNT(*) as rows_loaded 
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING 
GROUP BY source_file;

SELECT COUNT(*) as total_rows_loaded FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING;

-- Debug: Show sample of loaded data
SELECT col1, col2, col3, col4, col5, source_file 
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING 
LIMIT 5;

-- Remove bad rows
DELETE FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING WHERE symbol IS NULL OR symbol = '';

-- Debug: Check for duplicate symbols across files
SELECT 
    symbol,
    COUNT(*) as occurrence_count,
    COUNT(DISTINCT source_file) as file_count,
    LISTAGG(DISTINCT source_file, ', ') as files
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING 
GROUP BY symbol
HAVING COUNT(*) > 1
ORDER BY occurrence_count DESC
LIMIT 10;

-- Create deduplicated staging data
DELETE FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING 
WHERE (symbol, source_file) NOT IN (
  SELECT symbol, MIN(source_file) 
  FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING 
  GROUP BY symbol
);

-- Debug: Check staging data after deduplication
SELECT COUNT(*) as rows_after_dedup FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW_STAGING;

-- For now, skip the merge and just focus on loading data into staging
-- TODO: Add proper merge once we see what columns are actually loaded
SELECT 'Staging data loaded - check the sample above to see column structure' as MESSAGE;

-- Verify results
SELECT COUNT(*) AS total_overview_records FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW;

-- Sample records
SELECT SYMBOL, NAME, SECTOR, FISCAL_YEAR_END, LATEST_QUARTER, LOAD_DATE, UPDATED_AT
FROM FIN_TRADE_EXTRACT.RAW.COMPANY_OVERVIEW 
ORDER BY SYMBOL LIMIT 10;