-- Load/merge Alpha Vantage LISTING_STATUS (both active and delisted) from S3 into RAW.LISTING_STATUS
-- Automatically processes all CSV files in the listing_status/ prefix

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;
USE WAREHOUSE FIN_TRADE_WH;
USE ROLE ETL_ROLE;

-- 1) Create stage if needed
CREATE STAGE IF NOT EXISTS FIN_TRADE_EXTRACT.RAW.LISTING_STATUS_STAGE
  URL='s3://fin-trade-craft-landing/listing_status/'
  STORAGE_INTEGRATION = FIN_TRADE_S3_INTEGRATION;

-- 2) Create table if needed
CREATE TABLE IF NOT EXISTS FIN_TRADE_EXTRACT.RAW.LISTING_STATUS (
  SYMBOL_ID NUMBER(38,0) NOT NULL,
  SYMBOL VARCHAR(20) NOT NULL,
  NAME VARCHAR(255),
  EXCHANGE VARCHAR(64),
  ASSET_TYPE VARCHAR(64),
  IPO_DATE DATE,
  DELISTING_DATE DATE,
  STATUS VARCHAR(12),
  LOAD_DATE DATE DEFAULT CURRENT_DATE(),
  PRIMARY KEY (SYMBOL_ID)
);

-- 3) Load both active and delisted files into staging table
CREATE OR REPLACE TRANSIENT TABLE FIN_TRADE_EXTRACT.RAW.LISTING_STATUS_STAGING (
  SYMBOL VARCHAR(20),
  NAME VARCHAR(255),
  EXCHANGE VARCHAR(64),
  ASSET_TYPE VARCHAR(64),
  IPO_DATE VARCHAR(50),
  DELISTING_DATE VARCHAR(50),
  STATUS VARCHAR(12),
  LOAD_DATE DATE,
  SOURCE_FILE VARCHAR(500)
);

-- Debug: Check what files are in the stage
-- LIST @LISTING_STATUS_STAGE;

-- Load ALL CSV files (both active and delisted automatically)
COPY INTO FIN_TRADE_EXTRACT.RAW.LISTING_STATUS_STAGING (SYMBOL, NAME, EXCHANGE, ASSET_TYPE, IPO_DATE, DELISTING_DATE, STATUS, SOURCE_FILE)
FROM (
  SELECT $1, $2, $3, $4, $5, $6, $7, METADATA$FILENAME
  FROM @LISTING_STATUS_STAGE
)
FILE_FORMAT = (
  TYPE = 'CSV'
  SKIP_HEADER = 1
  FIELD_DELIMITER = ','
  RECORD_DELIMITER = '\n'
  NULL_IF = ('NULL', 'null', '', 'None')
  EMPTY_FIELD_AS_NULL = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
PATTERN = '.*\\.csv'
ON_ERROR = CONTINUE;
-- Note: PARALLEL parameter not supported for external stages (S3)
-- Snowflake automatically parallelizes based on number of files

-- Add load_date to staging data (use current date)
UPDATE FIN_TRADE_EXTRACT.RAW.LISTING_STATUS_STAGING SET load_date = CURRENT_DATE();

-- Remove bad rows
DELETE FROM FIN_TRADE_EXTRACT.RAW.LISTING_STATUS_STAGING WHERE SYMBOL IS NULL OR SYMBOL = '#NAME?';


-- Create deduplicated staging data (prefer active over delisted)
DELETE FROM FIN_TRADE_EXTRACT.RAW.LISTING_STATUS_STAGING 
WHERE (SYMBOL, SOURCE_FILE) NOT IN (
  SELECT SYMBOL, 
    CASE 
      WHEN COUNT(DISTINCT SOURCE_FILE) > 1 THEN 
        MIN(CASE WHEN SOURCE_FILE LIKE '%active%' THEN SOURCE_FILE END)
      ELSE MIN(SOURCE_FILE)
    END
  FROM FIN_TRADE_EXTRACT.RAW.LISTING_STATUS_STAGING 
  GROUP BY SYMBOL
);


-- Simple merge without complex subqueries
MERGE INTO FIN_TRADE_EXTRACT.RAW.LISTING_STATUS tgt
USING (
  SELECT
    ABS(HASH(SYMBOL)) % 1000000000 AS SYMBOL_ID,
    SYMBOL,
    NAME,
    EXCHANGE,
    ASSET_TYPE,
    TRY_TO_DATE(IPO_DATE, 'YYYY-MM-DD') AS IPO_DATE,
    TRY_TO_DATE(DELISTING_DATE, 'YYYY-MM-DD') AS DELISTING_DATE,
    STATUS,
    LOAD_DATE
  FROM FIN_TRADE_EXTRACT.RAW.LISTING_STATUS_STAGING
) src
ON tgt.SYMBOL_ID = src.SYMBOL_ID
WHEN MATCHED THEN UPDATE SET
  tgt.SYMBOL = src.SYMBOL,
  tgt.NAME = src.NAME,
  tgt.EXCHANGE = src.EXCHANGE,
  tgt.ASSET_TYPE = src.ASSET_TYPE,
  tgt.IPO_DATE = src.IPO_DATE,
  tgt.DELISTING_DATE = src.DELISTING_DATE,
  tgt.STATUS = src.STATUS,
  tgt.LOAD_DATE = src.LOAD_DATE
WHEN NOT MATCHED THEN INSERT (
  SYMBOL_ID, SYMBOL, NAME, EXCHANGE, ASSET_TYPE, IPO_DATE, DELISTING_DATE, STATUS, LOAD_DATE
) VALUES (
  src.SYMBOL_ID, src.SYMBOL, src.NAME, src.EXCHANGE, src.ASSET_TYPE, src.IPO_DATE, src.DELISTING_DATE, src.STATUS, src.LOAD_DATE
);

