

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;
USE WAREHOUSE FIN_TRADE_WH;
USE ROLE ETL_ROLE;

CREATE OR REPLACE STAGE FIN_TRADE_EXTRACT.RAW.EARNINGS_CALL_TRANSCRIPT_STAGE
    URL='s3://fin-trade-craft-landing/earnings_call_transcript/'
    STORAGE_INTEGRATION = FIN_TRADE_S3_INTEGRATION
    FILE_FORMAT = (
        TYPE = 'JSON'
        COMPRESSION = 'AUTO'
    );

LIST @FIN_TRADE_EXTRACT.RAW.EARNINGS_CALL_TRANSCRIPT_STAGE;

CREATE TABLE IF NOT EXISTS FIN_TRADE_EXTRACT.RAW.EARNINGS_CALL_TRANSCRIPT (
    TRANSCRIPT_DATA VARIANT,
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COPY INTO FIN_TRADE_EXTRACT.RAW.EARNINGS_CALL_TRANSCRIPT
    (TRANSCRIPT_DATA)
FROM @FIN_TRADE_EXTRACT.RAW.EARNINGS_CALL_TRANSCRIPT_STAGE
FILE_FORMAT = (TYPE = 'JSON');

SELECT 
    'Total Earnings Call Transcripts' as metric,
    CAST(COUNT(*) AS VARCHAR) as value
FROM FIN_TRADE_EXTRACT.RAW.EARNINGS_CALL_TRANSCRIPT;
