[project]
name = "lambda-deployment"
version = "1.0.0"
description = "Lambda deployment dependencies"
requires-python = ">=3.9"
dependencies = [
    "boto3>=1.26.0",
    "requests>=2.31.0",
    "python-dateutil>=2.8.2",
]