-- Fix ETL_WATERMARKS Table Schema
-- Drop the incorrect table and create the correct systematic watermarking structure

USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;
USE WAREHOUSE FIN_TRADE_WH;

-- 1. Drop the existing table with wrong schema
DROP TABLE IF EXISTS FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS;

-- 2. Create the correct ETL_WATERMARKS table for systematic watermarking
CREATE TABLE FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS (
    WATERMARK_ID NUMBER(38,0) IDENTITY(1,1) PRIMARY KEY,
    SYMBOL VARCHAR(20) NOT NULL,
    DATA_TYPE VARCHAR(50) NOT NULL,
    PROCESSING_STATUS VARCHAR(20) NOT NULL,
    LAST_PROCESSED_DATE DATE,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    ERROR_MESSAGE VARCHAR(2000),
    RETRY_COUNT NUMBER(10,0) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    
    CONSTRAINT UK_ETL_WATERMARKS_SYMBOL_DATA_TYPE UNIQUE (SYMBOL, DATA_TYPE)
);

-- 3. Verify the correct structure was created
SELECT 'Correct ETL_WATERMARKS table structure:' as MESSAGE;

SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'RAW' 
  AND TABLE_NAME = 'ETL_WATERMARKS'
ORDER BY ORDINAL_POSITION;

-- 4. Confirm table is empty and ready for watermark initialization
SELECT 'Table row count (should be 0):' as MESSAGE;
SELECT COUNT(*) as ROW_COUNT FROM FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS;

SELECT '✅ ETL_WATERMARKS table is now ready for systematic watermarking!' as STATUS;