USE DATABASE FIN_TRADE_EXTRACT;
USE SCHEMA RAW;
USE WAREHOUSE FIN_TRADE_WH;
USE ROLE ETL_ROLE;

-- Set the table name to reset
SET TABLE_NAME_TO_RESET = 'EARNINGS_CALL_TRANSCRIPT';

UPDATE FIN_TRADE_EXTRACT.RAW.ETL_WATERMARKS
SET LAST_FISCAL_DATE = NULL,
    FIRST_FISCAL_DATE = NULL,
    LAST_SUCCESSFUL_RUN = NULL,
    CONSECUTIVE_FAILURES = 0,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE TABLE_NAME = $TABLE_NAME_TO_RESET;
