name: ETF Profile Watermark ETL

on:
  workflow_dispatch:
    inputs:
      max_symbols:
        description: 'Maximum number of ETF symbols to process (blank = all)'
        required: false
        default: ''
        type: string
  schedule:
    - cron: '0 6 * * *'

jobs:
  etf_profile_watermark_etl:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Decode Snowflake private key
        run: echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY_DER_B64 }}" | base64 -d > snowflake_rsa_key.der
        working-directory: ${{ github.workspace }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/github_actions/requirements.txt

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-duration-seconds: 14400

      - name: Run ETF Profile ETL
        working-directory: ${{ github.workspace }}
        env:
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: fin-trade-craft-landing
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          if [ -n "${{ github.event.inputs.max_symbols }}" ]; then
            python scripts/etl/fetch_etf_profile_watermark.py --max-symbols "${{ github.event.inputs.max_symbols }}"
          else
            python scripts/etl/fetch_etf_profile_watermark.py
          fi

      - name: Clean up private key
        run: rm -f snowflake_rsa_key.der
        working-directory: ${{ github.workspace }}
