
name: Add Data Source Watermarks

on:
  workflow_dispatch:
    inputs:
      data_source:
        description: 'Data source to create watermarks for'
        required: true
        type: choice
        options:
          - TIME_SERIES_DAILY_ADJUSTED
          - COMPANY_OVERVIEW
          - BALANCE_SHEET
          - CASH_FLOW
          - INCOME_STATEMENT
          - INSIDER_TRANSACTIONS
          - EARNINGS_CALL_TRANSCRIPT
          - ETF_PROFILE
          - ALL_SOURCES
        default: 'TIME_SERIES_DAILY_ADJUSTED'

jobs:
  add-data-source-watermarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/github_actions/requirements.txt

      - name: Add Data Source Watermarks
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_PRIVATE_KEY_PATH: snowflake_rsa_key.der
        run: |
          echo "🚀 Creating data source watermarks"
          echo "📅 Timestamp: $(date)"
          echo "📊 Data source: ${{ github.event.inputs.data_source }}"
          python scripts/watermarking/create_individual_watermarks.py \
            --data-source "${{ github.event.inputs.data_source }}"

      - name: Save Results
        run: |
          echo "💾 Saving results..."
          cat > watermark_results.json << EOF
          {
            "data_source": "${{ github.event.inputs.data_source }}",
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "status": "completed"
          }
          EOF

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: data-source-watermarks-${{ github.event.inputs.data_source }}-${{ github.run_number }}
          path: watermark_results.json
          retention-days: 30